### ISSUE TITLE
config 扩展参考

### ISSUE THREAD

**Issue by yiminghe** [ant-tool/atool-build#114]
https://github.com/lewie9021/webpack-configurator

**Comment by pigcan** [comment]
感觉还不错

**Comment by afc163** [comment]
不错，可用。

**Comment by sorrycc** [comment]
:+1: 下一个版本可以加进去

**Comment by sorrycc** [comment]
another solution: https://github.com/survivejs/webpack-merge

**Comment by pigcan** [comment]
移步至 https://github.com/ant-tool/atool-build/issues/204
