### ISSUE TITLE
如何简化构建的 log 信息

### ISSUE THREAD

**Issue by afc163** [ant-tool/atool-build#115]
目前成功也会输出一大排信息。

`atool-build`

**Comment by pigcan** [comment]
https://github.com/ant-tool/atool-build/issues/50 之前也提过. 但是大家的意思是 如 issue

**Comment by afc163** [comment]
成功的时候太长了，感觉类似这样隐藏较好：

![](https://os.alipayobjects.com/rmsportal/lvKyNXVQuQDRkZL.png)
