### ISSUE TITLE
feature request - modifyVars at custom config

### ISSUE THREAD

**Issue by plandem** [ant-tool/atool-build#120]
Looks like it's impossible to modify modifyVars, right now.
```
loader: _extractTextWebpackPlugin2.default.extract('css?sourceMap!' + 'postcss-loader!' + ('less?{"sourceMap":true,"modifyVars":' + JSON.stringify(pkg.theme || {}) + '}'))

```
So looks like 'package.json' is the only way right now, but i need differ path for assets in dev and prod modes, so i would like to modify 'modifyVars' inside of custom webpack config.

case: differ path for assets in dev/prod modes

it also will help to remove such hacks:

index.less
```
@import "~antd/style/themes/default/index.less";
@import "custom.less";
@import "~antd/style/core/index.less";
```

custom.less
```
@assets-url: "/assets/";
@icon-url: "@{assets-url}/fonts/ant-font/ant-font";
@dash-type-url: "@{assets-url}/images/dash-types";
@icon-type-url: "@{assets-url}/images/dashboard-icons";
```

in would like to do something like this case i could use modifyVars and set: 
```
  webpackConfig.plugins.push(new webpack.DefinePlugin({
    'theme':  {
      'icon-url': 'assets/fonts/ant-font/ant-font',
      'assets-url': 'assets'
}
  }));

```

now i have to do it like this:
```
  var less_loader_id = null;

  webpackConfig.module.loaders.forEach(function(loader, loader_i) {
    if (loader.loader === 'babel') {
      // https://github.com/ant-design/babel-plugin-antd
      //loader.query.plugins.push('lodash');
      loader.query.plugins.push('antd');
    }

    if(process.env.PRODUCTION && loader.test && loader.test.toString() === (/\.less$/).toString() && loader.loader.indexOf('less?')) {
      less_loader_id = loader_i;
    }

    return loader;
  });

  //modify assets path for production
  if(less_loader_id !== null) {
    var loader = webpackConfig.module.loaders[less_loader_id];
    var query = loader.loader.substring(loader.loader.indexOf('less?') + 'less'.length);
    query = loaderUtils.parseQuery(query);
    query.modifyVars['access-url'] = '/admin/s/assets/';
    loader.loader = loader.loader.substring(0, loader.loader.indexOf('less?') + 'less?'.length) + JSON.stringify(query);
  }
```

**Comment by plandem** [comment]
to summarize - a way to provide theme via cli arg is more than enough:
```
atool-build --theme dev.json
```

**Comment by sorrycc** [comment]
I known this problem, it will be more convenience if have `--theme` arg. But I think there is some other solution for this? e.g.

1. use relative path, then use `webpack` to resolve path automatically
1. upload file to cdn, then use cdn's absolute path directly

**Comment by plandem** [comment]
Can you give more details about (1) - relative path.

**Comment by sorrycc** [comment]
Suppose you have `custom.less`, 

```css
@font-face {
    font-family: myFont;
    src: url(../fonts/my-font.woff);
}
```

after run `atool-build`, you will get files in `dist` like this:

```
+ dist
  - index.css
  - my-font.woff
```

Finally, deploy all files to dist to cdn.

**Comment by plandem** [comment]
in my case i need less magic and more predicted way. I mean we have same application for differ customers, but with own theme and some additional build settings. That's all. If it would be possibly to set theme via cli (like --theme customer1.json)  - it would be fine.

**Comment by pigcan** [comment]
https://github.com/ant-tool/atool-build/issues/176
