### ISSUE TITLE
Multi config 时是否考虑过采用多进程提高速度？

### ISSUE THREAD

**Issue by helloyou2012** [ant-tool/atool-build#121]
如：

```
# Main process
const cp = require('child_process');
for(let entry of entries) {
  let worker = cp.fork(__dirname + '/worker.js');
  worker.on('message', function (msg) {
    worker.kill();
  });
  worker.send(entry);
}
```

```
# worker.js
function doneHandler(err, stats) {
  ...
  process.send('done');
}
process.on('message', (entry) => {
  const config = getConfig();
  config.entry = entry;
  ...

  const compiler = webpack(config);
  compiler.run(doneHandler);
});
```

> PS: 线程管理可以采用 https://github.com/thisandagain/fork-pool

**Comment by sorrycc** [comment]
能快多少? 感觉构建的瓶颈并不在这里，而是在压缩上。

**Comment by helloyou2012** [comment]
恩，压缩去掉可以省一半时间，多进程可以再省一半

**Comment by helloyou2012** [comment]
不过要看CPU个数

**Comment by helloyou2012** [comment]
应该是webpack那边把MultiCompiler改成多进程比较好

**Comment by sorrycc** [comment]
刚想说这个，应该是 multi config 。(multi entry 不能用 worker 搞) 但是现在除了多语言，很少用 multi config，感觉需求比较小众。

**Comment by helloyou2012** [comment]
恩，那先关掉吧，不过后面可以考虑加一个--cluster参数开启多进程模式

**Comment by Liyuk** [comment]
多进程模式之后的版本会更新吗？

**Comment by sorrycc** [comment]
@Liyuk 你遇到什么问题? 为什么要多进程?

**Comment by Liyuk** [comment]
@sorrycc 项目大了打包速度降下来了，看了下以前gulp有用到worker-farm调用多核进行编译，希望webpack的编译速度有所提升。

**Comment by pigcan** [comment]
@Liyuk 我觉得你前提不太清楚

社区里面之所以有 worker 的应用那是建立在有多个 webpack.config.js 的基础上的，多个 webpack.config.js 互不影响当然可以利用多核来达到优化的目的。

但是在 atool-build 中，只有一个  webpack.config.js ，那怎么用 worker 呢 ?  如果你想要把 entry 拆分到多个 webpack.config.js 中去，那么 common 等等 webpack 的优化类动作全部失效了。

**Comment by helloyou2012** [comment]
通过多进程解决编译速度目前有两种：

1. [parallel-webpack](https://github.com/trivago/parallel-webpack) 用的 `worker-farm` ，但是 watch 模式时有问题：如果 config 数量大于 worker 数量时，多余的是不被执行的，不过可以通过每个 worker 服务于多个 config 来解决。
2. [happypack](https://github.com/amireh/happypack) 比较hack，通过 plugin 侵入 webpack 内部，将所有loader 的执行都转为多进程。

> 其实最好的方式是 webpack 修改内部执行逻辑，但成本比较高。

附个已经关了的 issue ：https://github.com/webpack/webpack/issues/2440

**Comment by helloyou2012** [comment]
@pigcan [happypack](https://github.com/amireh/happypack) 也适用于单个 config

**Comment by pigcan** [comment]
@helloyou2012   happypack 还真是第一次听说我关注下.

**Comment by Liyuk** [comment]
@pigcan @helloyou2012 谢谢
