### ISSUE TITLE
import react-component项目中的css，编译报错

### ISSUE THREAD

**Issue by foriacus** [ant-tool/atool-build#122]
```
import 'react-colors-picker/assets/index.css';   
```

报错信息：

```
 ERROR in ./~/atool-build/~/css-loader?sourceMap&-restructuring!./~/atool-build/~/postcss/lib/postcss.js!./~/react-colors-picker/assets/index.css

    Module build failed: Error: 
  is not a PostCSS plugin
        at Processor.normalize (/Users/foria/work/socialmng/ANT00910801_20160308_socialmng/static/node_modules/atool-build/node_modules/postcss/lib/processor.js:60:23)
        at new Processor (/Users/foria/work/socialmng/ANT00910801_20160308_socialmng/static/node_modules/atool-build/node_modules/postcss/lib/processor.js:23:29)
        at Object.postcss (/Users/foria/work/socialmng/ANT00910801_20160308_socialmng/static/node_modules/atool-build/node_modules/postcss/lib/postcss.js:55:12)
```

版本："atool-build": "~0.6.1"
node : v5.3.0

```
"devDependencies": {
    "babel-core": "^6.4.0",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-register": "^6.6.5",
    "dora": "0.2.x",
    "dora-plugin-atool-build": "0.4.x",
    "dora-plugin-hmr": "^0.2.x",
    "dora-plugin-livereload": "^0.2.0",
    "dora-plugin-proxy": "^0.5.x",
    "eslint": "~1.10.3",
    "eslint-config-airbnb": "~2.1.0",
    "eslint-plugin-react": "~3.12.0"
  },
  "entry": {
    "app": "./app.jsx"
  },
  "dependencies": {
    "@alipay/ajax": "~2.0.6",
    "antd": "~0.12.8",
    "@alipay/rc-g2": "~2.0.0-beta2",
    "atool-build": "~0.6.1",
    "babel-plugin-antd": "^0.1.3",
    "babel-polyfill": "~6.5.0",
    "css-animation": "~1.0.3",
    "es5-shim": "~4.0.5",
    "events": "~1.0.1",
    "flux": "~2.0.3",
    "gregorian-calendar": "~3.0.0",
    "gregorian-calendar-format": "~3.0.1",
    "jquery": "~2.2.1",
    "jsuri": "~1.3.0",
    "keymirror": "~0.1.1",
    "object-assign": "~2.0.0",
    "react": "~0.14.7",
    "react-dom": "~0.14.7",
    "react-router": "~2.0.0",
    "react-colors-picker": "~2.3.0",
    "store": "~1.3.16",
    "react-addons-linked-state-mixin": "~0.14.7"
  },
  "babel": {
    "presets": [
      "es2015",
      "react",
      "stage-0"
    ],
    "plugins": [
      "add-module-exports"
    ]
  }
```

**Comment by sorrycc** [comment]
执行 npm run build 报错还是 npm run dev 报错?

**Comment by sorrycc** [comment]
我本地试过 `import 'react-colors-picker/assets/index.css'; ` 没有问题，如果是 npm run dev 报错，试着把依赖升级到最新试试。

## 升级方法：

参考：https://github.com/ant-design/antd-init/blob/master/boilerplate/package.json

注意 `dora-plugin-atool-build` 需要换成 `dora-plugin-webpack` (scripts 的 plugin 也要改)

**Comment by afc163** [comment]
要是可以一键升级就好了，把这些配置进行二次打包？

**Comment by sorrycc** [comment]
我也还没想好怎么方便地升级，是写一个脚本呢，还是再封装个类 spm 的工具。

**Comment by afc163** [comment]
类似内部 flaming-water 的东西？

提供脚手架输出能力，入口稳定，配置统一管理。

现在内部的 chair 和 sf 等工具的配置也是五花八门。

**Comment by sorrycc** [comment]
`提供脚手架输出能力，入口稳定，配置统一管理。`，antd-init 不就是做这件事的么? flaming-water 解决配置升级的问题了吗?

**Comment by afc163** [comment]
使用  flaming-water 的包，后续基本只要升级  flaming-water 的依赖即可。

**Comment by afc163** [comment]
使用  flaming-water 的包，后续基本只要升级  flaming-water 的依赖即可。而现在 antd-init 只有项目开始前调用一次，无法被依赖。

**Comment by sorrycc** [comment]
听起来和之前的 spm 一样啊，`init` + `build` + `server` 。

**Comment by sorrycc** [comment]
不想再做个大一统的工具了，更倾向于可以搞个 `atool-doctor`，提供环境建议(比如 tnpm 建议用 4)和依赖升级的功能。

**Comment by afc163** [comment]
类似 GreenKeeper 好了，各种建议。

**Comment by oversky86** [comment]
升级之后，还是不行，运行命令tnpm run _dora_proxy,附上完整package.json
"scripts": {
    "build_dev": "atool-build -o ./dist",
    "build": "atool-build -o ./dist/${npm_package_family}/${npm_package_name}/${npm_package_version} --no-compress --devtool sourcemap",
    "dev": "dora -p 8001 --plugins proxy?watchDirs=./mock/, atool-build",
    "server": "antd server --proxy",
    "proxy": "./node_modules/node/bin/node ./node_modules/antd-bin/bin/antd server --proxy /${npm_package_name}/${npm_package_version} --public-path /${npm_package_name}/${npm_package_version}",
    "build_antd": "rm -rf dist && mkdir -p dist/${npm_package_name}/${npm_package_version} && antd-build && mv dist/*.js dist/*.map dist/*.css dist/${npm_package_name}/${npm_package_version}/",
    "_dora_proxy": "dora -p 8001 --plugins webpack,proxy,hmr,livereload?enableJs=false",
    "_dora_build": "atool-build",
    "_dora_move": "mkdir -p dist/${npm_package_name}/${npm_package_version} && mv dist/* dist/${npm_package_name}/${npm_package_version}/"
  },
  "repository": "http://svnhz.alipay.net/svn/socialmng/",
  "author": "liuqin.sheng@alipay.com",
  "contributors": [
    {
      "name": "yumu",
      "email": "shiliang.sl@alibaba-inc.com"
    }
  ],
  "license": "ISC",
  "devDependencies": {
    "antd-bin": "~0.10.2",
    "yargs": "~3.27.0",
    "gulp": "^3.9.0",
    "gulp-shell": "^0.2.8",
    "babel-core": "^6.4.0",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-register": "^6.6.5",
    "dora": "0.2.x",
    "dora-plugin-webpack": "0.6.x",
    "dora-plugin-hmr": "^0.2.x",
    "dora-plugin-livereload": "^0.2.0",
    "dora-plugin-proxy": "^0.5.x",
    "eslint": "~1.10.3",
    "eslint-config-airbnb": "~2.1.0",
    "eslint-plugin-react": "~3.12.0"
  },
  "engines": {
    "install-node": "4.2.2"
  },
  "entry": {
    "app": "./app.jsx"
  },
  "dependencies": {
    "@alipay/ajax": "~2.0.6",
    "antd": "~0.12.8",
    "@alipay/rc-g2": "~2.0.0-beta2",
    "antd-build": "~0.4.4",
    "atool-build": "~0.6.1",
    "babel-plugin-antd": "^0.1.3",
    "babel-polyfill": "~6.5.0",
    "css-animation": "~1.0.3",
    "es5-shim": "~4.0.5",
    "events": "~1.0.1",
    "flux": "~2.0.3",
    "gregorian-calendar": "~3.0.0",
    "gregorian-calendar-format": "~3.0.1",
    "jquery": "~2.2.1",
    "jsuri": "~1.3.0",
    "keymirror": "~0.1.1",
    "object-assign": "~2.0.0",
    "react": "~0.14.7",
    "react-dom": "~0.14.7",
    "react-router": "~2.0.0",
    "react-colors-picker": "~2.3.0",
    "store": "~1.3.16",
    "react-addons-linked-state-mixin": "~0.14.7"
  },
  "babel": {
    "presets": [
      "es2015",
      "react",
      "stage-0"
    ],
    "plugins": [
      "add-module-exports"
    ]
  }

**Comment by afc163** [comment]
格式...

**Comment by pigcan** [comment]
atool-doctor 挺好的 XD

**Comment by sorrycc** [comment]
@oversky86 (观通) 的问题已解决，本地有 antd-bin 和 atool-build 的依赖，应该是有冲突导致的。
