### ISSUE TITLE
css optimize (Remove unused CSS)

### ISSUE THREAD

**Issue by helloyou2012** [ant-tool/atool-build#124]
> css-loader 里自带 cssnano，暂时没法处理这种情况

目前效果：

input
```
.hello {
  color: red;
}
.hello {
  color: blue;
}
```

output
```
.hello{color:red;color:blue;}
```

**Comment by afc163** [comment]
用压缩不就好了？

**Comment by helloyou2012** [comment]
默认执行 `atool-build` 不是自带压缩么？

**Comment by pigcan** [comment]
嗯 自带压缩. 

你提的需求 (Remove unused CSS)   这个优化其实是个伪命题. 

比如在移动端业务里面就有需求 比如存在两种单位的边距 以适配 ios 和 Android

**Comment by pigcan** [comment]
样式的压缩应该是有参数可配置的.
