### ISSUE TITLE
autoprefixer support IE9

### ISSUE THREAD

**Issue by afc163** [ant-tool/atool-build#129]
```js
postcss: [
  autoprefixer({
    browsers: ['last 2 versions', 'Firefox ESR', '> 1%', 'ie >= 8']
  })
]
```

现在的样式不会生成 `-ms-` 前缀，导致 IE9 支持的部分 css3 属性失效。

- https://github.com/postcss/autoprefixer#webpack
- https://github.com/ai/browserslist#queries

**Comment by sorrycc** [comment]
autoprefix 的 bug 吗?

**Comment by afc163** [comment]
是 autoprefixer 默认支持的浏览器范围是 `> 1%, last 2 versions, Firefox ESR`，貌似不包括 IE9，需要手动加入。

https://github.com/postcss/autoprefixer/issues/630
