### ISSUE TITLE
build 后，保持 src 下目录结构的层级一致

### ISSUE THREAD

**Issue by SMbey0nd** [ant-tool/atool-build#131]
希望确保 build 后的目录结构与 src 内保持一致，原因以下几点：

1. HTML 文件之间存在互链，拍平会直接影响到互链，不留意很可能导致故障
1. 如果一定需要改造为拍平结构，那么还可能会引发下面两个问题：
  1. 原来不同的目录中存在相同的 HTML 文件名，拍平后导致重名报错
  1. 路径修改后涉及到外部投放链接的变更，这个是未知的，致命的
1. 目录结构的组织不合理，目录杂乱缺少可维护性

**Comment by jsw0528** [comment]
居然会不一致。。。

**Comment by sorrycc** [comment]
路径问题和 webpack 保持一致，我不希望额外加的 hack，会引入很多意想不到的问题。上面列的这些问题你在拍平目录的基础上再想想，我觉得都是有方案的。

**Comment by SMbey0nd** [comment]
@sorrycc 我完全能理解你的想法。但现实情况问题是，

1. 这件“额外的事情”在之前的 amb/spm 时代就已经做了并落地到了所有的移动项目中。如果在一个新版工具当中反而取消了这个功能，站在使用者的角度而言，是一种倒退。同时，工具的向下兼容也是工具升级本身应该考虑和做到的事情。
2. 如果工具不能提供向下兼容，那么至少要提供旧版本的并存。但目前 spmjs.io 的强制下线，意味着并没有为用户提供后路。因此强制升级请一定考虑尽少的改动和变更。目前的这个变更之大很难以被业务所接受。
3. 我并不觉得 webpack 提供的所有方案是最适合当前业务的方案，很多设计思路都持有保留意见。所以“与 webpack 保持一致”的出发点到底是什么？是否值得再思考一下

**Comment by sorrycc** [comment]
线下讨论了。

**Comment by sorrycc** [comment]
总结下，有两个方案：

1. 遵从 webpack 的规则，所有文件打包后拍平。html 文件命名冲突通过命名约定的方式解决
1. 除 html 外文件拍平。html 不走 atool-build/webpack 的流程处理，另外通过工具进行单独的复制和路径修复。

html 处理工具的伪代码：

```javascript
glob.src('./src/**/*.html')
  .pipe(fixPath)
  .dest('./dist/');
```

推荐方案 1。
