### ISSUE TITLE
is it possible to build-in react-intl translator?

### ISSUE THREAD

**Issue by plandem** [ant-tool/atool-build#136]
Here is my **package.json**:
```
  "scripts": {
    "dev": "cross-env PRODUCTION=0 dora -p 8001 --plugins atool-build,proxy,hmr",
    "build": "npm run build:packed",
    "build:packed": "cross-env PRODUCTION=1 atool-build -o ./dist/${npm_package_family}/${npm_package_name}/${npm_package_version}",
    "build:unpacked": "cross-env PRODUCTION=1 atool-build --no-compress -o ./dist/${npm_package_family}/${npm_package_name}/${npm_package_version}",
    "build:i18n-gather": "rimraf i18n-messages && BABEL_ENV=i18n babel --quiet src > /dev/null",
    "build:i18n": "npm run build:i18n-gather && babel-node --presets es2015 scripts/translate.js",
    "lint": "eslint --ext .js,.jsx src"
  }
```

as you can see there is 'build:i18n" command. i'm sure it's quite common feature that will be required by many projects.

Here is my **translate.js**
```
import * as fs from 'fs';
import { sync as globSync } from 'glob';
import { sync as mkdirpSync } from 'mkdirp';
import pkg from '../package.json';

const MESSAGES_PATTERN = './i18n-messages/**/*.json';
const LANG_DIR = './locale/';
const LANG_PATTERN = LANG_DIR + '*.js';

if(!pkg.i18n) {
  throw new Error("Can't find i18n settings at package.json");  
}

const langList = pkg.i18n.locale || [ ];
if(!Array.isArray(langList) || !langList.length) {
  throw new Error("Locale settings must be array. E.g.: [\"en\", \"ru\"]");  
}

/**
 * All available locales 
 */
const originLangs = { };

langList.forEach(lang => {
  originLangs[lang] = { };
});

/**
 * Default locale that was using at application 
 */
const defaultLang = pkg.i18n.default || langList[0];

/**
 * Override messages for default lang with newly extracted from apps, or preserve existing
 */
const defaultOverride = typeof(pkg.i18n.override) !== 'undefined' ? pkg.i18n.override : true;

/**
 * Aggregates the default messages that were extracted from the example app's
 * React components via the React Intl Babel plugin. An error will be thrown if
 * there are messages in different components that use the same `id`. The result
 * is a flat collection of `id: message` pairs for the app's default locale.
 */
const defaultMessages = globSync(MESSAGES_PATTERN)
  .map((filename) => fs.readFileSync(filename, 'utf8'))
  .map((file) => JSON.parse(file))
  .reduce((collection, descriptors) => {
    descriptors.forEach(({id, defaultMessage}) => {
      if (collection.hasOwnProperty(id)) {
        throw new Error(`Duplicate message id: ${id}`);
      }

      collection[id] = defaultMessage;
    });

    return collection;
  }, { });

/**
 * Load existing locales
 */
globSync(LANG_PATTERN).map((filename) => {
  originLangs[filename.split('/').pop().split('.').shift()] = require('../' + filename);
});

const defaultMessagesArr = Object.keys(defaultMessages).map((id) => [id, defaultMessages[id]]);
const newLangs = { };

/**
 * Update locales
 */
Object.keys(originLangs).forEach(lang => {
  if(defaultOverride && lang === defaultLang) {
    newLangs[lang] = defaultMessages;
  } else {
    newLangs[lang] = defaultMessagesArr.reduce((collection, [id]) => {
      collection[id] = originLangs[lang][id] || originLangs[defaultLang][id] || defaultMessages[id] || '';
      return collection;
    }, { });
  }
});

mkdirpSync(LANG_DIR);

/**
 * Save updated locales to disk
 */
Object.keys(originLangs).forEach(lang => {
  fs.writeFileSync(LANG_DIR + lang + '.js',
    'module.exports = ' + JSON.stringify(newLangs[lang], null, 2) + ';'
  );
});
```

and here is **.babelrc**
```
{
  "env": {
    "i18n": {
      "presets": [ "es2015", "stage-0", "react" ],
      "plugins": [
        [ "react-intl", {
          "messagesDir": "./i18n-messages",
          "enforceDescriptions": false
        }]
      ]
    }
  }
}
```

I'm sure it would be right to integrate this feature into atool-build. I see it like special option at **package.json**:
```
  "i18n": {
    "locale": ["en", "ru"],
    "override": false
  },
  "scripts": {
    "build:i18n": "npm run atool-build --i18n",
  }
```

this **i18n** options will replace **originLangs** and **defaultOverride**. As default language we can take just first language from **locale** array of **i18n** settings.

**Comment by plandem** [comment]
there are 2 steps: 1) grab messages from react application  and 2) transform it into locale file.

**Comment by plandem** [comment]
it's for: **react-intl** and **babel-plugin-react-intl**

**Comment by pigcan** [comment]
@jaredleechn you may introduce your solution here

**Comment by jaredleechn** [comment]
@plandem you can see the repository of [atool-l10n](https://github.com/ant-tool/atool-l10n) for solving common localization problem

You can using built-in or manual-writting middlewares to customize the solution, maybe transfer defaultMessages to zh, maybe process through translate center such as google, youdao

And here's the demo  [intl-example](https://github.com/ant-design/intl-example)

**Comment by plandem** [comment]
what is behaviour in case of already existing translation?

ok, here is cases:
1) no translation, add new
2) existing translation, keep existing
3) removed translation, remove deprecated

is it possible to accomplish?

**Comment by jaredleechn** [comment]
The 1st and 2nd are ready in atool-l10n

> 3) removed translation, remove deprecated

I don't understand enough about this case. Do u mean if removing keys from source code(eg: `FormatMessage`) will delete the keys in generated locale file? Or vice versa?

All the translation operations are based on the keys generated by [summary middleware](https://github.com/ant-tool/atool-l10n#built-in-middlewares), which read all the `*.json` files generated maybe by`babel-plugin-react-intl` scanning the source code, then fetch from meta, from local, from translation server, and reduce the best one, and save...

BTW, if u use `babel-plugin-react-intl`, better set cache to false for generating all keys everytime, [ref](https://github.com/ant-design/intl-example/blob/master/webpack.config.js#L10)

**Comment by plandem** [comment]
(3)  - in case when some messages were removed from code also remove it at locale files. I.e. "cleanup" and remove anything that is not using.

**Comment by jaredleechn** [comment]
Yeah, it can make it

**Comment by jaredleechn** [comment]
You can try it out first, any issue or suggestion is welcome 😊
