### ISSUE TITLE
usage: about webpack.optimize.CommonsChunkPlugin

### ISSUE THREAD

**Issue by benjycui** [ant-tool/atool-build#137]
If I pack a library(e.g. antd) with atool-build, it will generate antd.js and common.js, and I have to import two files(antd.js && common.js) to use this library. Otherwise, an error will be thrown. 

![image](https://cloud.githubusercontent.com/assets/3580607/14407509/bb53390a-fefe-11e5-8a2e-8815bcb1dedb.png)

I don't know this before Google it. So, maybe you had better to document this is READMD.md.

> If you are going to pack a library with atool-build, please remove webpack.optimize.CommonsChunkPlugin plugin.

Or add a CLI option to make it easier to pack a library?

**Comment by pigcan** [comment]
如果是要新起一个组件的话可以使用 component-init 

如果要在现有基础上删除 common， 参考 https://github.com/ant-tool/component-init/blob/master/boilerplate/webpack.config.js#L5

**Comment by benjycui** [comment]
这个我知道，主要是觉得至少要在文档里说一下，这样对刚上手的人友好点。

然后 atool-build 应该不仅是用来打包组件，也可以用来打包 jQuery 这样的库，所以不一定可以用 component-init

**Comment by zinkey** [comment]
确实是个问题，之前也有开发来问为什么两个文件。这里要不就先在文档里面说清楚一下。

**Comment by pigcan** [comment]
在 1.0 中默认关闭 

https://github.com/ant-tool/atool-build/issues/192
