### ISSUE TITLE
atool-build项目中使用html loader问题

### ISSUE THREAD

**Issue by 270584936** [ant-tool/atool-build#150]
这段loader配置有用吗？有了这个配置html loader（https://github.com/webpack/html-loader） 就无法使用了。
`
{ test: /\.html?$/, loader: 'file?name=[name].[ext]' }
`

**Comment by sorrycc** [comment]
```
 { test: /\.html?$/, loader: 'file?name=[name].[ext]' } 
```

这行的目的是说在 js 里 import 一个 html 文件时，html 文件会被复制到 dist 目录。如果有不同需求，可以通过 `webpack.config.js` 覆盖这个配置。

**Comment by pigcan** [comment]
嗯 关于覆盖操作可以看看 http://ant-tool.github.io/spm-to-atool-build.html 这个文档，

里面有大概介绍了 怎么覆盖 loader 或者 plugin 的方式

**Comment by 270584936** [comment]
http://ant-tool.github.io/spm-to-atool-build.html 中loader的覆盖配置貌似在使用html loader（https://github.com/webpack/html-loader）时无效。

**Comment by sorrycc** [comment]
检查下你的代码，webpackConfig 是 plain object，都是可以覆盖的。
