### ISSUE TITLE
Try to speed up the process of uglifyjs

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#151]

**Comment by sorrycc** [comment]
- http://stackoverflow.com/a/33836205/1270774
- https://blog.mozilla.org/webdev/2011/10/25/go-speed-racer/

**Comment by zinkey** [comment]
Eslint can check out the problem first.

**Comment by sorrycc** [comment]
给 UglifyjsPlugin 关 sourceMap 能快一点：

```
sourceMap: false
```

https://gitter.im/webpack/webpack/archives/2014/10/31

**Comment by sorrycc** [comment]
http://webpack.github.io/analyse/#hints
webpack build 分析

**Comment by sorrycc** [comment]
http://webpack.github.io/docs/build-performance.html

**Comment by sorrycc** [comment]
https://github.com/webpack/extract-text-webpack-plugin/issues/86
extract-text-webpack-plugin 和 uglifyjs 配置使用的时候会很慢。

**Comment by sorrycc** [comment]
https://github.com/mishoo/UglifyJS2/issues/216
Speed build by reduced processing of pre-minified dependencies

**Comment by pigcan** [comment]
看下来似乎也还是没啥好的解决方案.

**Comment by afc163** [comment]
sourceMap 线上调试错误时有用吧。

**Comment by sorrycc** [comment]
@afc163 是的，不准备关这个。慢的主要原因也不在这。

**Comment by pigcan** [comment]
由 https://github.com/ant-tool/atool-build/issues/206 跟进
