### ISSUE TITLE
支持 async await

### ISSUE THREAD

**Issue by zinkey** [ant-tool/atool-build#153]
- babe-plugin-syntax-async-functions
- babel-plugin-transform-regenerator
- babel-polyfill

### 方案1
```javascript
import 'atool-build/babel-polyfill'
```
### 方案2
```bash
$ atool-build --babel-polyfill
```

**Comment by sorrycc** [comment]
babel-polyfill 为啥放 atool-build 下?

**Comment by zinkey** [comment]
类似 atool-build/lib/babel-polyfill

**Comment by sorrycc** [comment]
项目代理里手动引 babel-polyfill 不可以吗?

**Comment by zinkey** [comment]
可以。

**Comment by chj-damon** [comment]
最后还是没有说明白怎么让async/await生效呀。我现在在webpack.config.js里面加入了：webpackConfig.babel.plugins.push('transform-runtime');
babel-plugin-transform-runtime和babel-runtime都安装了，但是还是无法使用async。请问是还需要做什么配置吗？
