### ISSUE TITLE
webpack.config.js 配置问题

### ISSUE THREAD

**Issue by yuweilan** [ant-tool/atool-build#154]
在https://github.com/ant-design/antd-init中，
atool-build如何配置将css，js和img放入不同的文件夹？
webpack.config.js中这些entry,output,devtool, resolve, resolveLoader,node,loader,plugins
build到dist的时候，html怎么添加进去？谢谢，麻烦了

**Comment by sorrycc** [comment]
> atool-build如何配置将css，js和img放入不同的文件夹？

不可以，只能输出在同级目录里。

> build到dist的时候，html怎么添加进去？

在 `.js` 文件里 import html 文件。

**Comment by yuweilan** [comment]
build到dist的时候，html怎么添加进去？
在 .js 文件里 import html 文件。
求问这个html在哪个js中加？（有点懵逼）

另外webpack.config.js中这些entry,output,devtool, resolve, resolveLoader,node,loader,plugins能自行重新配置么？我改了output没有达到效果，不知道怎么改，谢谢

**Comment by yuweilan** [comment]
还有打包到dist文件里的东西怎么preview，我用过gulp的preview，到这里不知道怎么弄了

**Comment by pigcan** [comment]
pkg.entry 中的字段是作为一个页面的入口

所以 index 对应 path/to/index.js 

而对应的 index.html 就直接在 path/to/index.js 中直接 require('path/to/index.html') 即可

**Comment by yuweilan** [comment]
@pigcan 谢谢，另，请问在https://github.com/ant-design/antd-init中，打包的dist文件怎么跑起来，上一个问题忘了问跑起来需要html么？（小白肉牛满面的感谢

**Comment by pigcan** [comment]
你问的是调试么 ?

```bash
tnpm run start
```
浏览器中打开 `http://127.0.0.1:port` 
然后你的页面可以通过`http://127.0.0.1:port/entryName.html` 访问到

在 html 中需要调整下资源文件

```
<script src="common.js"></script>
<script src="entryName.js"></script>
<link href="entryName.css" ...... />
```

**Comment by yuweilan** [comment]
@sorrycc 大神，求问https://github.com/ant-design/antd-init 中，生成的dist文件
![qq 20160509094902](https://cloud.githubusercontent.com/assets/11817795/15101874/4ca11a52-15cb-11e6-8bb1-c5a4b2aad50d.png)
没有html文件可以调试预览么（如果可以怎么调，谢谢，实在是麻烦了）？
另外在jsx文件里import可以引入html，但是生成的hash怎么传入？谢谢

**Comment by pigcan** [comment]
用 antd-init 出来的项目不就有可以预览的方式么.

**Comment by helloyou2012** [comment]
参考文档：https://github.com/ant-design/antd-init/tree/master/boilerplate

> 构建和调试是两种模式，构建是将代码编译到dist下方便发布代码，调试是开启server动态编译（编译结果文件存在内存中）。项目中是有页面的，就是最外面的index.html，这是本地调试用的。另：执行脚本参见：https://github.com/ant-design/antd-init/blob/master/boilerplate/package.json#L31

**Comment by yuweilan** [comment]
@pigcan @helloyou2012 谢谢大神，get，最后只剩下怎么将map.json的hash映射到html中了
