### ISSUE TITLE
引用第三方组件，有的是用scss有的是用less.通过build能不能整合在一起？

### ISSUE THREAD

**Issue by ksh033** [ant-tool/atool-build#162]
我引用了一个第三方的组件，使用的是scss。我想编译的时候把less和scss的样式整合在一起。需要在 
webpack.config.js里做什么配置吗？
**我现在的做法**

> 在webpack.config.js加入scss的加载器
> webpackConfig.module.loaders.unshift({test: /\.scss$/, loader: "style!css!sass"});
> 然后在jxs require('./index.scss')
> index.scss
> @import "~amazeui-touch/src/scss/amazeui-touch";
> 编译时报报错
```
 > ERROR in ./src/entry/index.jsx
 > Module not found: Error: Cannot resolve module 'style' in F:\shine\nodeproject\appdemo\src\entry
 > @ ./src/entry/index.jsx 23:0-23
```

**Comment by pigcan** [comment]
写成这个试试   `style-loader!css-loader! sass-loader`

**Comment by ksh033** [comment]
@pigcan 
谢谢，这个是可以,但是build后scss编译后的css合并不到index.css里面.是否需要我再做什么样的配置

**Comment by pigcan** [comment]
在 index.js 里面 

```
require('path/to/xx.less');
require('path/to/xxx.sass');
```

这么写不行么?

**Comment by ksh033** [comment]
require('path/to/xxx.sass');这上是可以
但是我的xxx.sass里面写的是
@import "~amazeui-touch/src/scss/amazeui.touch.scss";
amazeui.touch.scss里的样式没用合并到index.css

**Comment by ksh033** [comment]
我只在webpack.config.js配置
 webpackConfig.module.loaders.unshift({test: /.scss$/, loader:"style-loader!css-loader!sass-loader"});
是否还需要再做其它的配置？

**Comment by pigcan** [comment]
那这个 scss 的文件打包出来在哪儿

**Comment by ksh033** [comment]
就是没有任何反应。webpackConfig是用antd-build默认的配置。
`plugins: [new _webpack2.default.optimize.CommonsChunkPlugin('common', commonName), new _extractTextWebpackPlugin2.default(cssFileName, {
      disable: false,
      allChunks: true
    }), new _webpack2.default.optimize.OccurenceOrderPlugin()]`
是不是默认会把所有的require("样式")自动合并到index.css里？

**Comment by pigcan** [comment]
样式是跟着 entry 走的. 即 entry 如果有 index index1 如果刚好在 index 和 index1 中又有引用样式，那么就会有 index.css 和 index1.css，该样式会包含所有引用链上的样式。

你可以尝试在你的脚本里面直接 require 对应模块的样式看看

**Comment by ksh033** [comment]
好像可以了。。我再试试谢谢。

**Comment by iiitmahesh** [comment]
@ksh033 @pigcan  Did u solved the problem. Please share scss configuration ???
