### ISSUE TITLE
support typescript

### ISSUE THREAD

**Issue by yiminghe** [ant-tool/atool-build#167]
refer: https://github.com/react-component/rc-tools

**Comment by sorrycc** [comment]
https://github.com/react-component/rc-tools/blob/master/lib/getWebpackCommonConfig.js

**Comment by pigcan** [comment]
我来跟进吧, 不过优先级低些

**Comment by yiminghe** [comment]
一会就搞好了，不用低了，类库要启动 ts 重写了
