### ISSUE TITLE
strip-loader

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#17]
生产环境 strip 掉 debug，然后推荐用 debug 包来进行调试。

https://github.com/yahoo/strip-loader

**Comment by zinkey** [comment]
业务代码中用debug调试的情况不多吧

**Comment by sorrycc** [comment]
debug 用来打印日志啊，console.log 调试完了还要删除，https://www.npmjs.com/package/debug，我看蔡伦在这么用。

**Comment by zinkey** [comment]
ok

**Comment by zinkey** [comment]
如需要自己配置 webpack。
