### ISSUE TITLE
请问把对应的文件替换掉后，要在哪个目录下输入什么命令才会生成对应的映射文件

### ISSUE THREAD

**Issue by aw6658913** [ant-tool/atool-build#170]

**Comment by aw6658913** [comment]
没有对应的教程 看了 不会搭建啊  替换掉之后搞不懂要在哪个目录下输入什么命令 才能把自己要编译的文件 编译过去

**Comment by pigcan** [comment]
没能明白你要表达的内容

**Comment by aw6658913** [comment]
我搭了环境把lib跟src下对应的文件给替换成atool-build-master的lib以及src下的，然后之后呢~要运行什么命令把test/fixtures下的文件编译到expect文件夹下（PS：我理解的没错吧?expect是编译fixtures后生成的）

**Comment by pigcan** [comment]
建议你了解下 pkg 的 scripts 内容
关于 fixtures 和 expect 是测试时所需，fixtures 指的是需要测试的特性，而 expect 则是对特性输出内容的验证。 

> expect 是编译 fixtures 后生成的

这个理解是错的
