### ISSUE TITLE
我是否可以选择webpack的版本

### ISSUE THREAD

**Issue by azl397985856** [ant-tool/atool-build#171]
我现在想用webpack2的 tree-shaking ， 而你的项目是基于webpack1.x 。  那么我可以配置webpack版本吗？如果不能想要实现类似 eliminate unused code怎么做

**Comment by afc163** [comment]
http://venturehacks.com/articles/ask-forgiveness-not-permission

**Comment by azl397985856** [comment]
。。。。不懂什么意思

**Comment by pigcan** [comment]
目前不能指定 webpack 的版本
