### ISSUE TITLE
webpack -json 报错

### ISSUE THREAD

**Issue by azl397985856** [ant-tool/atool-build#172]
使用atool-build ， webpack.config export的是function, 而 我需要生成stat.json。 需要使用webpack -json
\> stat.json 。 需要webpack.config export的是object，请问这个怎么解决，或者说atool-build有没有这样的功能接口

**Comment by pigcan** [comment]
https://github.com/ant-tool/atool-build/blob/master/bin/atool-build#L14

**Comment by azl397985856** [comment]
谢谢~

**Comment by azl397985856** [comment]
我也看过这个文件，但是我的atool-build是老版本的，没有这个json 选项。 ^_^
