### ISSUE TITLE
build出来的文件和 --json打出来的文件不同

### ISSUE THREAD

**Issue by azl397985856** [ant-tool/atool-build#173]
![Uploading image.png…]()
![Uploading build.png…]()
具体信息：
> atool-build -o ./sms_assets/test_build/

Child
    Time: 138079ms
                         Asset     Size  Chunks             Chunk Names
                    account.js   5.7 kB      14  [emitted]  account
                   pressSms.js   152 kB   0, 13  [emitted]  pressSms
                    signSms.js   145 kB       2  [emitted]  signSms
                deliverySms.js   146 kB       3  [emitted]  deliverySms
                 arrivalSms.js   146 kB       4  [emitted]  arrivalSms
                       home.js   114 kB       5  [emitted]  home
               systemConfig.js   104 kB       6  [emitted]  systemConfig
              smsStatistics.js   102 kB       7  [emitted]  smsStatistics
                    smsBill.js  91.9 kB       8  [emitted]  smsBill
       smsMarketingAnalysis.js  91.1 kB       9  [emitted]  smsMarketingAnalysis
                smsRecharge.js  86.8 kB      10  [emitted]  smsRecharge
             rechargeRecord.js  66.9 kB      11  [emitted]  rechargeRecord
                     record.js   5.5 kB      12  [emitted]  record
                       care.js  6.05 kB      13  [emitted]  care
               smsMarketing.js   274 kB       1  [emitted]  smsMarketing
                        app.js  6.63 kB      15  [emitted]  app
                  marketing.js  5.53 kB      16  [emitted]  marketing
                     common.js   934 kB      17  [emitted]  common
                      index.js   346 kB      18  [emitted]  index
             buyerListModal.js  51.3 kB      19  [emitted]  buyerListModal
           smsTemplateModal.js  52.6 kB      20  [emitted]  smsTemplateModal
    smsMarketingDetailModal.js   199 kB      21  [emitted]  smsMarketingDetailMo                                                                                                                                                                                               dal
        care_shortLinkModal.js    20 kB  22, 26  [emitted]  care_shortLinkModal
      care_smsTemplateModal.js  17.7 kB      23  [emitted]  care_smsTemplateModa                                                                                                                                                                                               l
       smsMarketingSmsModal.js  7.41 kB      24  [emitted]  smsMarketingSmsModal
                  areaModal.js  11.7 kB      25  [emitted]  areaModal
             shortLinkModal.js  5.22 kB      26  [emitted]  shortLinkModal
                     index.css   307 kB      18  [emitted]  index
                    index.html  1.44 kB          [emitted]
    Child html-webpack-plugin for "index.html":
             Asset    Size  Chunks       Chunk Names
        index.html  535 kB       0

BG204936@bg204936 MINGW64 /e/ltcrm/trunk/client/front
$ npm run json

> ltcrm-front@1.6.0 json E:\ltcrm\trunk\client\front
> atool-build --json -o ./stats

Generate Json File: stats\build-bundle.json
Child
    Time: 730925ms
                         Asset     Size      Chunks             Chunk Names
                    account.js   5.7 kB      14, 17  [emitted]  account
                   pressSms.js   888 kB   0, 13, 17  [emitted]  pressSms
                    signSms.js   882 kB       2, 17  [emitted]  signSms
                deliverySms.js   882 kB       3, 17  [emitted]  deliverySms
                 arrivalSms.js   882 kB       4, 17  [emitted]  arrivalSms
                       home.js   156 kB       5, 17  [emitted]  home
               systemConfig.js   840 kB       6, 17  [emitted]  systemConfig
              smsStatistics.js   839 kB       7, 17  [emitted]  smsStatistics
                    smsBill.js   828 kB       8, 17  [emitted]  smsBill
       smsMarketingAnalysis.js   786 kB       9, 17  [emitted]  smsMarketingAnal                                                                                                                                                                                               ysis
                smsRecharge.js   129 kB      10, 17  [emitted]  smsRecharge
             rechargeRecord.js  66.9 kB      11, 17  [emitted]  rechargeRecord
                     record.js  5.51 kB      12, 17  [emitted]  record
                       care.js  6.06 kB      13, 17  [emitted]  care
               smsMarketing.js  1.01 MB       1, 17  [emitted]  smsMarketing
                        app.js  6.63 kB      15, 17  [emitted]  app
                  marketing.js  5.53 kB      16, 17  [emitted]  marketing
                     common.js  1.62 kB          17  [emitted]  common
                      index.js   541 kB      18, 17  [emitted]  index
             buyerListModal.js  51.3 kB      19, 17  [emitted]  buyerListModal
           smsTemplateModal.js  52.6 kB      20, 17  [emitted]  smsTemplateModal
    smsMarketingDetailModal.js   199 kB      21, 17  [emitted]  smsMarketingDeta                                                                                                                                                                                               ilModal
        care_shortLinkModal.js    20 kB  22, 17, 26  [emitted]  care_shortLinkMo                                                                                                                                                                                               dal
      care_smsTemplateModal.js  17.7 kB      23, 17  [emitted]  care_smsTemplate                                                                                                                                                                                               Modal
       smsMarketingSmsModal.js  7.42 kB      24, 17  [emitted]  smsMarketingSmsM                                                                                                                                                                                               odal
                  areaModal.js  11.7 kB      25, 17  [emitted]  areaModal
             shortLinkModal.js  5.22 kB      26, 17  [emitted]  shortLinkModal
                     index.css   307 kB      18, 17  [emitted]  index
                    index.html  1.44 kB              [emitted]
    Child html-webpack-plugin for "index.html":
             Asset    Size  Chunks       Chunk Names
        index.html  535 kB       0

**Comment by azl397985856** [comment]
怀疑是commonChunckPlugin没有起作用

**Comment by pigcan** [comment]
之后直接通过插件的方式 如 https://www.npmjs.com/package/stats-webpack-plugin 来进行 stats.json 的生成
