### ISSUE TITLE
jsx 写错时，错误提示「不正确」，定位不到准确错误位置。

### ISSUE THREAD

**Issue by warmhug** [ant-tool/atool-build#174]
真正的错误原因是这里、漏了小括号：
![image](https://cloud.githubusercontent.com/assets/2011119/16453647/2b46d872-3e40-11e6-8a6a-1f9cd40bb11e.png)
但 terminal 报错是这样的：
![image](https://cloud.githubusercontent.com/assets/2011119/16453674/4b31415e-3e40-11e6-946d-b18816aa81c7.png)
Chrome dev tool 报错是这样的：
![image](https://cloud.githubusercontent.com/assets/2011119/16453706/7325fc18-3e40-11e6-99ff-666a606e7120.png)

**不仅仅是定位不到准确错误位置、连出错的提示信息也几乎完全没用~**

**Comment by pigcan** [comment]
可能因为不同的 devtool 导致

https://github.com/dora-js/dora-plugin-webpack/blob/master/src/index.js#L35

目前默认为

```js
webpackConfig.devtool = '#cheap-module-source-map';
```

这是基于性能的选择，如果可以忽略调试时的性能，可以尝试直接使用 soucemap.
