### ISSUE TITLE
feat: package.json theme 支持字符串类型

### ISSUE THREAD

**Issue by yiminghe** [ant-tool/atool-build#176]
如果是字符串类型，查找对应的文件（以 . 或 / 开头），或对应的模块名

```
theme:'./node_modules/antui-config/index.js', // 'antui-config'
```

antui-config/index.js
```
module.exports = function() {
  return {
    "brand-6":"red"
  };
};
```

**Comment by sorrycc** [comment]
@pigcan 看下。

**Comment by s774977731** [comment]
package.json theme 有没有具体的流程 ？？

**Comment by mrbenlearnjs** [comment]
请问下“theme:'./node_modules/antui-config/index.js', // 'antui-config'”配置在哪里？

**Comment by pingan1927** [comment]
package.json @mrbenlearnjs

**Comment by jaredleechn** [comment]
> module.exports = function() {
>   return {
>     "brand-6":"red"
>   };
> };

这里配置文件里支持自定义的 keys 都包含哪些？是 [theme/default.less](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less) 里面这些么？

@yiminghe @pingan1927 @pigcan

**Comment by pingan1927** [comment]
@jaredleechn 是的，都在这里了。

@mrbenlearnjs `"theme": "./node_modules/kb-merchant-theme/index.js"`

这里的`kb-merchant-theme`是我自己发布的一个npm模块。通过install来进行引用。

**Comment by goldingking** [comment]
要使用"theme": "./node_modules/kb-merchant-theme/index.js"这种方式，必须使用atool-build编译才行吧？还需要哪些其他的配置？

**Comment by xdimh** [comment]
不使用atool-build 打包,直接使用自己配置的webpack,怎么做才能使得颜色修改生效？
