### ISSUE TITLE
modifyVars is not working anymore (still)

### ISSUE THREAD

**Issue by plandem** [ant-tool/atool-build#186]
I posted early. But right now, it's critical again (it was not working for us from that time, but was not critical):
https://github.com/ant-tool/atool-build/issues/135

package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "private": true,
  "entry": {
    "babel": "babel-polyfill",
    "en": "./src/entry/en.js",
    "ru": "./src/entry/ru.js",
    "index": "./src/entry/index.jsx"
  },
  "theme": {
    "assets-url": "/zzz"
  },
  "i18n": {
    "locale": [
      "en",
      "ru"
    ],
    "override": false
  },
  "dependencies": {
...
```

as you can see we have **assets-url** var here.

Here is our main less:
```
@import "~antd/lib/style/themes/default.less";
@import "custom.less";
@import "~antd/lib/style/core/index.less";
@import "~antd/lib/style/components.less";

//override default settings for some components that can't be set via 'custom.less'
.@{input-number-prefix-cls} {
   width: 100%;
 }
```

here is custom.less
```
@assets-url: "/admin/s/assets";
@icon-url: "@{assets-url}/fonts/ant-font/ant-font";
@dash-type-url: "@{assets-url}/images/dash-types";
@icon-type-url: "@{assets-url}/images/dashboard-icons";
```

As you can see by default, we have this vars with differ value (package.json overrides it for ***zzz***)

Here is logs:
```
 npm run dev

> cross-env PRODUCTION=0 dora -p 8001 --plugins webpack,hmr,proxy,livereload?enableJs=false

Dev mode:  true
Adjust assets path for dev...
{ test: /\.module\.less$/,
  loader: '/Users/andrey/Projects/web/luxmsbi-admin/node_modules/extract-text-webpack-plugin/loader.js?{"remove":true}!css?sourceMap&modules&localIdentName=[local]___[hash:base64:5]!!postcss!less-loader?{"sourceMap":true,"modifyVars":{"assets-url":"/zzz"}}' }
          proxy: load rule from proxy.config.js
          proxy: listened on 8989
     livereload: listening on 35729
📦  1402/1402 build modules
webpack: bundle build is now finished.
```

as you can see we have modified var here!

But at browser i still have previous vars:
https://www.dropbox.com/s/whvfr3q5x46fqc8/Screenshot%202016-07-20%2016.50.14.png?dl=0

and my less for these items like this:
https://www.dropbox.com/s/js3eksj8l34sgcd/Screenshot%202016-07-20%2016.51.20.png?dl=0

How to fix it?!

**Comment by pigcan** [comment]
when you work with string path  you should use like this

```
@assets-url: '"path/to/image/file"';
```

and you'd better use config file, e.g. 

https://github.com/ant-tool/atool-build/tree/master/test/fixtures/build-theme

**Comment by plandem** [comment]
Well, it's worked now. Problem was at string path. I would advice to include this (string path) into example/fixture, because it's not obvious :(

**Comment by pigcan** [comment]
ok  next release I would include this to test.
