### ISSUE TITLE
atool-build 增强移动端的兼容性

### ISSUE THREAD

**Issue by pigcan** [ant-tool/atool-build#190]
`last 2 versions, Firefox ESR, > 1%, ie >= 8, iOS >= 8, Android >= 4`

http://browserl.ist/?q=last+2+versions%2C+Firefox+ESR%2C+%3E+1%25%2C+ie+%3E%3D+8%2C+iOS+%3E%3D+8%2C+Android+%3E%3D+4

[目前配置](https://github.com/ant-tool/atool-build/blob/04ad014e6a6f84602d259bb462557bb5ce22d665/src/getWebpackCommonConfig.js#L152)

**Comment by afc163** [comment]
ref https://github.com/ant-design/ant-design-mobile/issues/35
