### ISSUE TITLE
讨论：atool-build 1.0 需求

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#192]
比如：
- #191, use babel-plugin-transform-runtime by default
- 简化配置，可以是类 create-react-app 的 eject 功能，或者基于配置的封装
- #151, Try to speed up the process of uglifyjs
- #64, webpack 2
- [webpack-validator](https://github.com/js-dxtools/webpack-validator)
- 内置 css-modules, 现在配置起来很麻烦，https://github.com/ant-design/babel-plugin-antd/issues/46#issuecomment-238139185
- 默认不加 common 插件
- Better error message, like [this](https://github.com/geowarin/tarec/pull/16), [friendly-errors-webpack-plugin](https://github.com/geowarin/friendly-errors-webpack-plugin)
- [case-sensitive-paths-webpack-plugin](https://github.com/Urthen/case-sensitive-paths-webpack-plugin)
- `babelrc: false`
- babel-plugin-antd 与 require.ensure 冲突，考虑 webpack2，https://github.com/ant-design/ant-design/issues/2782
- [webpack-fail-plugin](https://github.com/TiddoLangerak/webpack-fail-plugin)
- 一直会生成 common.css

**Comment by yiminghe** [comment]
不要内置 css-modules，另外 antd 不能被 css-module 的, 可以给个快速设置的方法？

```js
webpackConfig = cssModules(webpackConfig)
```

**Comment by pigcan** [comment]
其实我都不太赞成用 css-module --！ 在合理的命名空间内感觉不太需要吧。

**Comment by sorrycc** [comment]
node_modules 下不走 css-modules，项目级别的 css 和 less 才走，这样就不影响 antd 了。

**Comment by pigcan** [comment]
atool-build 下一个大版本我个人会更加倾向于 

1. 要么非常能方便用户修改配置，现在修改配置的方式，还要判断是否有某个实例的方式实在是无法接受。

2. 要么 atool-build 转变成只生成配置的工具，脚手架里面直接用 webpack 来调用配置打包

**Comment by sorrycc** [comment]
不用 css-modules，怎么解决命名冲突的问题?

**Comment by afc163** [comment]
css-modules 挺好的，命名空间太难约束了。

**Comment by pigcan** [comment]
可能和开发习惯有关，我写样式全部会加特定业务的前缀。
重名概率很小吧。

**Comment by pigcan** [comment]
atool-build 中 common 的逻辑还要保留么

**Comment by yiminghe** [comment]
默认不 common 吧

**Comment by pigcan** [comment]
我另外一个想法是把 atool-build 往 eslint 配置的方向上靠，每个团队或者每个业务其实都有更适合的配置。 团队可以有自己的 xxx-build-config， 而与 atool-build 的关系可以是 extend。

**Comment by sorrycc** [comment]
更新了，默认不加 common 插件。

**Comment by jaredleechn** [comment]
- feat: 把组件开发中的 compile 也集成进去，做为一个单独的功能，compile js && lessc less

目前组件开发的 babel-plugin 基本都内置到了 atool-build 里，如果还需要自己管理依赖关系和 compile 非常麻烦，同时极小的可能会出现 compile 和 build 结果不一致的问题（使用了不同的 babel

**Comment by bo3en** [comment]
走 css-modules 会导致无法本地部署antd 的图标，需要去特别指定某个文件不走 css-modules 来重新引入antd的样式文件，希望可以手动开启css-modules，或者可以特别指定某些文件不走css-modules，不需要过多的配置

**Comment by sorrycc** [comment]
@bo3en 参考[这个配置](https://github.com/dvajs/dva-cli/blob/1a4cb33/boilerplates/app/webpack.config.js#L21-L38)，让 node_modules 下的不走，项目目录的走，能解决你的问题吗?

**Comment by bo3en** [comment]
@sorrycc 感谢回复，但是现在我就是用的这个配置。
因为要本地部署antd图标所以需要在index.less里去import antd的样式，这样的话 antd的全局样式就会丢失，会全部被css-modules加上前缀。现在我的解决方法就是单独配置index.less不走css-modules，但是配置很麻烦。
如果不是自己去引用antd样式，通过babel-plugin-import引用，antd默认还是会请求cdn的图标库。

还有个问题就是 如果使用babel-plugin-import引入样式，还会导致无法覆盖antd的样式，写theme的话也会很麻烦。
