### ISSUE TITLE
npm link 导致 resolveDir 错误

### ISSUE THREAD

**Issue by jaredleechn** [ant-tool/atool-build#194]
在项目目录 link 了子组件，子组件的文件在过 webpack 的 loader 和 plugin 的时候，resolveDir 会变成子组件的目录，导致项目指定的一些 plugin 找不到

**Comment by jaredleechn** [comment]
尝试在 https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L75 把项目目录增加到 modulesDirectories，也没有效果

增加 resolve.fallback 也没有效果

**Comment by pigcan** [comment]
在 webpack@2 应该就可以了. 大版本中来解决吧.

**Comment by jaredleechn** [comment]
还出现一个问题，react 中，项目目录和组件目录的 node_modules 都有一个 react，经常报 `only a reactowner can have refs. you might be adding a ref to a component`

https://github.com/facebook/react/issues/5538

**Comment by pigcan** [comment]
如上这个问题应该重新安装下 deps 就好了

**Comment by jaredleechn** [comment]
在组件目录吗？还是项目目录？

在项目目录会导致 link 失效
