### ISSUE TITLE
alias 配置没有达到预期效果

### ISSUE THREAD

**Issue by Xylitol-lin** [ant-tool/atool-build#195]
````javascript
var newResolve = {
  alias: {
    'config': path.join('xxxx')
  }
}
webpackConfig.resolve = Object.assign({}, webpackConfig.resolve, newResolve)
````

````
import config from 'config'
````

我想利用 resolve.alias 的功能，达到引入文件的时候不写一长串路径。代码如上，但是当我执行 `atool-build` 的时候，atool 会帮我执行 `npm i config` ，而不是从 resolve.alias 中找 config

**Comment by pigcan** [comment]
* 没有必要 assign 吧 atool-build 没有设置 alias

```
webpackConfig.resolve.alias = {
  .......
}
```

* 修改下 config

```
alias: {
    'config': path.resolve('relative/to/config')
}
```

**Comment by sorrycc** [comment]
是 `npm start` 的时候自动安装了 config 吧? 需要禁用掉 dora-plugin-webpack 的 npm install 功能。

```bash
dora --plugins 'webpack?disableNpmInstall'
```

详见：
https://github.com/dora-js/dora-plugin-webpack#options

**Comment by Xylitol-lin** [comment]
禁用掉 dora-plugin-webpack 的 npm install 功能就可以了，谢谢
