### ISSUE TITLE
.less中的@keyframes无法保持原来的命名

### ISSUE THREAD

**Issue by hellobbq** [ant-tool/atool-build#197]
#### 你做了什么？
index.jsx :
`import './common.less'`

common.less
`@keyframes aaa {}`
or 
`:global { 
@keyframes aaa {}
 }`
#### 你期待的结果是：

index.css
`@keyframes aaa {}`

#### 实际上的结果：

index.css
`@keyframes aaa____hellxsfsdfsdf {}`

**Comment by pigcan** [comment]
你给的场景复现不了你提的问题。

如果是有以 xxx.module.less 来命名的会被命中启用 css-module

启用 css-module 的情况下可以如下使用。

```
import style from './custom.less';
...
return <div className={style.classname} />;

```

**Comment by hellobbq** [comment]
`import style from './custom.less';
...
return <div className={style.classname} />;`

custom.less 
`
.classname {
animation: pika cubic-bezier(0.785, 0.135, 0.15, 0.86) infinite;
}
@keyframes pika{
0% {opacity: 0;}
100% {opacity: 1;}
}`

**Comment by pigcan** [comment]
你的 webpack.config.js 怎么写的. 
案例你最好给个测试 repo.

**Comment by pigcan** [comment]
1. 在最新 antd-init 中的脚手架中会默认开启 css-module 关注下你的 webpack.config.js 是否有相关配置
2. 使用 .module.less 结尾的文件默认启用 css-module


由于测试中并未发现 issue 反馈者问题现关闭

**Comment by liaili** [comment]
你好，关于下面这两点，可以详细描述下吗？
1.在最新 antd-init 中的脚手架中会默认开启 css-module 关注下你的 webpack.config.js 是否有相关配置
2.使用 .module.less 结尾的文件默认启用 css-module
