### ISSUE TITLE
打包是否支持目录映射？

### ISSUE THREAD

**Issue by aw6658913** [ant-tool/atool-build#200]
比如我在entry下建立文件夹a和b，打包时指定a和b下的js，分别打包到dist下a和b中，看了几天打包源码没整明白，不知道你们是否有相关的配置

**Comment by sorrycc** [comment]
不支持隐射，webpack 的机制是拍平的。

**Comment by aw6658913** [comment]
这样的话一个项目不是页面得都一个人来开发，编译的js文件都必须要命名不能统一一个名字，即使命名了不同人开发的可能名字也会冲突，是不是不大好？

**Comment by sorrycc** [comment]
有冲突的话在定义 entry 的时候就会发现了，可以加前缀之类的。
