### ISSUE TITLE
关于output的问题。

### ISSUE THREAD

**Issue by ITtong** [ant-tool/atool-build#201]
默认打包输出在dist文件夹中，我现在需要把js文件输出在public文件夹中的js文件夹中，把css输出在public文件夹中的css 文件夹中，把图片输出在public文件夹中的img文件夹中。
这该怎么配置啊，在pkg.json文件中配置entry字段吗？求大神告知。

**Comment by pigcan** [comment]
`$(npm bin)/atool-build -o dist/xxx`

只能把资源文件定向输出到某个文件夹

但是被 css 或者 less 引用的图片，css，js 最终都会被拍平，即资源文件都会保持在同一层目录

这是 webpack 的逻辑

**Comment by ITtong** [comment]
那我可以将dist文件夹的名称修改成public吗？如果能，怎么修改。 @pigcan

**Comment by pigcan** [comment]
在上面一个回复中不是和你说了么  -o 

学会用 atool-build --help

**Comment by ITtong** [comment]
@pigcan 好的，谢谢大神。
