### ISSUE TITLE
引入 babel-react-optimize

### ISSUE THREAD

**Issue by afc163** [ant-tool/atool-build#208]
https://github.com/thejameskyle/babel-react-optimize

@pigcan

**Comment by pigcan** [comment]
放在 1.0 中去实现吧

默认应用在 env 为 production 时

**Comment by afc163** [comment]
可能有 bug ，不要默认开启。

**Comment by pigcan** [comment]
如果有 bug 的话，就暂 hold 吧

如果是默认不开启靠配置项来开启的话感觉太小题大做了

或者随脚手架。
