### ISSUE TITLE
atool-compile

### ISSUE THREAD

**Issue by jaredleechn** [ant-tool/atool-build#209]
- feat: 把组件开发中的 compile 也集成进去，做为一个单独的功能，compile js && lessc less

目前组件开发的 babel-plugin 基本都内置到了 atool-build 里，如果还需要自己管理依赖关系和 compile 非常麻烦，同时极小的可能会出现 compile 和 build 结果不一致的问题（使用了不同的 babel

**Comment by jaredleechn** [comment]
traced in #192

**Comment by pigcan** [comment]
不通过如下这种方式来实现
```bash
$ atool-build --compile-only 
```

实现可以按照目前 transformLess 来实现一个 transformJS

**Comment by jaredleechn** [comment]
但我觉得 atool-build 应该是做为一个集 compile、build 一体的解决方案，原本 build 做的事情应该是 1.0  的一个子集

如果用户还要自己写脚本去 compile，这很麻烦～

**Comment by pigcan** [comment]
因为你使用 --compile-only 的方式实质是要脱离出 webpack 的，而没有了 webpack 的 resolve 你并不能获取所有的依赖关系. 

继而就会变成你需要去指明需要 compile 的对象是什么脚本，是什么 less，个人感觉这和 build 工具很混淆视听。

比较偏向基于 transformJS 和 transformLess 独立写个 bin

**Comment by jaredleechn** [comment]
```
//package.json
bin: {
  atool-build: './bin/build.js',
  atool-compile: './bin/compiler.js'
}
```
```bash
$ atool-compiler src lib
```
这样怎么样？

compile 自动处理 less 或者 js

**Comment by pigcan** [comment]
靠谱
