### ISSUE TITLE
HtmlWebpackPlugin使用问题

### ISSUE THREAD

**Issue by lys623** [ant-tool/atool-build#210]
![12](https://cloud.githubusercontent.com/assets/4364314/18535294/98ff467a-7b25-11e6-82bf-70f1a66f3c6f.png)

如图，的确会生成dist/main/resources/templates/app.html，但是app.html里面的内容并不是模版src/templates/app.html里面的内容，而是demo中的index.html内容，怎么弄呢？

**Comment by pigcan** [comment]
不明白你的代码组织所以给不了你确切的解决方案。

可以移除下 atool-build 中内置的处理 html 的 loader - file loader

**Comment by jaredleechn** [comment]
@lys623 

这个问题和 atool-build 无关吧，应该是 htmlWebpackPlugin 配置出现了问题，猜测可能是模版文件路径错误（或未发布

另外你这个是一个什么需求？给组件写 Demo？

**Comment by van0303** [comment]
直接 push HtmlWebpackPlugin 进去，的确有 @lys623 说的问题，主要的影响是 file-loader 导致；
考虑删除，或者按需要重新构造默认的 loader

**Comment by pigcan** [comment]
> 移除下 atool-build 中内置的处理 html 的 loader - file-loader

**Comment by jaredleechn** [comment]
> 移除下 atool-build 中内置的处理 html 的 loader - file-loader

这个是不是意味着不能在 js 里面 require html 文件啦？

**Comment by pigcan** [comment]
可以的，移除 file-loader 作为 html 的 loader 后

可以自行在 webpack.config.js 中增加处理 html 的loader

**Comment by paranoidjk** [comment]
同遇到这个问题，考虑把 `HtmlWebpackPlugin` 的使用简化集成进来？

**Comment by pigcan** [comment]
@paranoidjk 可以下个版本中集成进来吧

**Comment by zllc** [comment]
求问如何去掉内置的file-loader

**Comment by pigcan** [comment]
看 @van0303 回复
