### ISSUE TITLE
使用加载antd样式的babel插件时，公用的样式并没有被提取到common.css中

### ISSUE THREAD

**Issue by chentony** [ant-tool/atool-build#214]
如题，如复现不了请@我～ 谢谢～

**Comment by afc163** [comment]
@pigcan

**Comment by pigcan** [comment]
指的是没有用 babel 插件时就可以?

**Comment by chentony** [comment]
忽略我吧 很少有组件全部页面都使用了  所以没生成在common里
 现在单页面按需加载更好的  如果在common里全量加载也不太好

**Comment by afc163** [comment]
所以，其实 common 其实是有效的？

**Comment by chentony** [comment]
所有页面都被引用的组件才会被提取， 没试 页面比较多 这个应该是没问题的。

**Comment by pigcan** [comment]
@afc163 有效的 

目前内置的 common 的逻辑是需要所有的 entry 中被引用到才会并入 common 这个 chunk

但是这个是可以调整的，http://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin
