### ISSUE TITLE
antd-tools, ant-tool, atool-build, dora

### ISSUE THREAD

**Issue by lefter** [ant-tool/atool-build#217]
搞晕了，这几个工具是什么关系，怎么分工的？
antd-tools
https://github.com/ant-design/antd-tools

ant-tool
https://github.com/ant-tool

atool-build
https://github.com/ant-tool/atool-build/

dora
https://github.com/dora-js/dora

**Comment by pigcan** [comment]
ant-tool 是一个 group 的名字，内部包含了基础构建 atool-build, 测试 atool-test, 文档 atool-doc 等服务

dora 是一个中性的插件化的调试服务，插件有 webpack, proxy, simulator 等

antd-tools 应该是基于 ant-tool 工具体系针对 antd 的封装。

**Comment by sorrycc** [comment]
Duplicated, https://github.com/dvajs/dva/issues/119
