### ISSUE TITLE
modules 里的html loader

### ISSUE THREAD

**Issue by aliencyl7** [ant-tool/atool-build#218]
为什么html loader 是这样的
`{ test: /\.html?$/, loader: 'file?name=[name].[ext]' }`
而不是html-loader 
`{ test: /\.html$/, loader: 'html' }`

**Comment by pigcan** [comment]
因为在默认需求中 html 只需要复制到构建的目标目录即可，此时用 file-loader 比较顺理成章。

当然如果你的 html 涉及到模板，压缩等问题时，此时 file-loader 就不适用了，需要覆盖默认的处理。

**Comment by aliencyl7** [comment]
但是我的js 和css 一般都会加上hash，所以不是简单的复制，我现在做法是移除这个loader，然后添加我自己的html loader， 好像直接覆盖也没有用，一定要移除

**Comment by pigcan** [comment]
覆盖默认处理意思就是更换 atool-build 中对于处理 `.html ` 的 loader. 表现为在  webpack.config.js 中删除原有处理，然后新增一个处理。
