### ISSUE TITLE
html引入hash静态资源的问题

### ISSUE THREAD

**Issue by wonyun** [ant-tool/atool-build#219]
@sorrycc @pigcan 大神们，遇到一个问题就是atool-build编译后的html中的js和css资源如何替换为hash过的对应资源，使用`html-webpack-plugin`后把我页面中js、css资源替换同时，也把我对应的dom内容节点也替换为文本为`index.html`，这是我配置的问题么，引入hash过的资源有什么更好的解决方法么，谢谢！
代码为：
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="/index.css" />
</head>
<body>
  <div id="root"></div>
  <script src="/common.js"></script>
  <script src="/index.js"></script>
</body>
</html>
```
使用html-webpack-plugin后编译成：
```html
<head>
    <link href="index-81a01312eadb19806e5c.css?6d98b89588dbc9e8c582" rel="stylesheet">
</head>index.html
<script type="text/javascript" src="common-f199d66b5c1b19b2ec17.js?6d98b89588dbc9e8c582"></script>
<script type="text/javascript" src="index.js-6d98b89588dbc9e8c582?6d98b89588dbc9e8c582"></script>
```
根目录下`webpack.config.js`中`HtmlWebpackPlugin`的配置如下：
```javascript
webpackConfig.plugins.push(
      new HtmlWebpackPlugin({
          template: 'entries/index.html', // 源模板文件
          filename: './index.html', // 输出文件【注意：这里的根路径是module.exports.output.path】
          inject: true,
          hash: true,
          chunks: ["common",'index'] //index为entry中的配置项
      })
  );
```

**Comment by wonyun** [comment]
与这个问题[201](https://github.com/ant-tool/atool-build/issues/210)类似：
就是atool-build内置的`file-loader`与`HtmlWebpackPlugin`中的template配置起冲突，导致template配置的模板路径（路径配置正确）不起作用，出现上面编译后只有`head`和`script`标签，head之后为模板配置文件的文件名。

解决办法：
* 去掉atool-build自带的file-loader
* 在入口`index.js`中去掉html文件的引入

掉到这个坑里面了，折腾了一个大半夜晚，觉得atool-build的`tutorial`应该有提示这种问题的。
另外，虽然问题折腾半天解决了，但是不明白具体原因是为什么这样，请大神们赐教，非常感谢！

**Comment by zhongjie-chen** [comment]
用你的方法解决了；去掉loader 你是改源码？
