### ISSUE TITLE
atool-build -w 和atool-build出来的内容有差异

### ISSUE THREAD

**Issue by zhaoxingming** [ant-tool/atool-build#222]
项目主要环境：
node:v5.2.0
tnpm:3.18.1
antd:1.0.0
atool-build:0.6.5

项目执行atool-build -w的时候，修改文件，编译出来的js文件跟atool-build编译出来的文件不同。
atool-build -w编译的目标文件不能执行。且主要区别如下：

**其中-的是正常的atool-build出来的目标文件。+[] 部分，是atool-build -w出来的目标文件。
感觉atool-build -w的过程中，没有对依赖的文件偏移量做替换为代码的工作。不知道什么原因。不知道是否遇到过这种情况。**
`--- /Users/zhaoxingming/Work/tmp/applyError/question-list.js Tue Oct 11 17:05:14 2016`
`+++ /Users/zhaoxingming/Work/tmp/applyError/wrong/question-list.js Tue Oct 11 17:02:47 2016`
`@@ -7979,14 +7979,7 @@`
`-/***/ function(module, exports, __webpack_require__) {`
`-`
`-  // Thank's IE8 for his funny defineProperty`
`-  module.exports = !__webpack_require__(66)(function(){`
`-    return Object.defineProperty({}, 'a', {get: function(){ return 7; }}).a != 7;`
`-  });`
`-`
`-/***/ },`
`+[578, 66],`
`-/***/ function(module, exports, __webpack_require__) {`
`-`
`-  var dP         = __webpack_require__(265)`
`-    , createDesc = __webpack_require__(270);`
`-  module.exports = __webpack_require__(65) ? function(object, key, value){`
`-    return dP.f(object, key, createDesc(1, value));`
`-  } : function(object, key, value){`
`-    object[key] = value;`
`-    return object;`
`-  };`
`-`
`-/***/ },`
`+[580, 265, 270, 65],`
`-/***/ function(module, exports, __webpack_require__) {`
`-`
`-  // fallback for non-array-like ES3 and non-enumerable old V8 strings`
`-  var cof = __webpack_require__(258);`
`-  module.exports = Object('z').propertyIsEnumerable(0) ? Object : function(it){`
`-    return cof(it) == 'String' ? it.split('') : Object(it);`
`-  };`
`-`
`-/***/ },`
`+[581, 258],`

**Comment by zhangjh** [comment]
加不加--no-compress的出来也不一样。。我项目里不加参数压缩的版本可以，加了后不压缩的版本就报错。。

**Comment by zhangjh** [comment]
真是坑，浪费了大半天，也是用了-w，发现改个很简单的if else都会报错，看到楼主说的才想起来重新打包，结果就不报错了。。

**Comment by pigcan** [comment]
估计 UglifyJsPlugin 不能用在 watch 模式下这个在后续中改掉
