### ISSUE TITLE
如何生成带目录的html？

### ISSUE THREAD

**Issue by kchjxxgh** [ant-tool/atool-build#223]
如果我的文件结构是这样的，如何才能build之后output：admin/index.html?

> entry
> │  index.html
> │  index.js
> │  index.less
> └─admin
>         index.html
>         index.js
>         index.less

在package.json里面的entry，这么写：

>   "entry": {
>     "index": "./entry/index.js",
>     "admin/index": "./entry/admin/index.js"
>   },

结果，最终生成的是，admin/index.js里面引用的是admin/index.html这个文件：

> ```
>               Asset       Size  Chunks             Chunk Names
>          index.html  296 bytes          [emitted]
>            index.js     294 kB       0  [emitted]  index
>  admin/index.js     294 kB       1  [emitted]  admin/index
> admin/index.css   87 bytes       1  [emitted]  admin/index
>           index.css   87 bytes       0  [emitted]  index
> ```

在生成的里面只有一个index.html，请问我如何生成admin/index.html呢？

**Comment by sorrycc** [comment]
文件拍平了，换 admin.html 估计就好了。
