### ISSUE TITLE
集成 svg-sprite-loader? 

### ISSUE THREAD

**Issue by yiminghe** [ant-tool/atool-build#225]
https://github.com/ant-design/ant-design-mobile/blob/master/components/icon/index.web.tsx

**Comment by pigcan** [comment]
这个需求不太适合放进 atool-build 内吧

**Comment by yiminghe** [comment]
antd-mobile 需要这个 loader，每个项目都自己配下？

**Comment by pigcan** [comment]
那就内置一个吧. - -！

**Comment by pigcan** [comment]
目前该插件配置上有什么需求？

**Comment by yiminghe** [comment]
{
        test: /\.svg$/,
        loader: 'svg-sprite',
      },

**Comment by afc163** [comment]
这个有进展么，antd-mobile@1.x 可测。

**Comment by warmhug** [comment]
这个还是先不要集成。svg icon 的使用方式最终还没完全确认下来，有可能不使用 webpack config 文件里的配置，而是在写代码时直接 require 处理 、还要确认有没有问题
https://github.com/ant-design/ant-design-mobile/blob/master/components/icon/index.md
![image](https://cloud.githubusercontent.com/assets/2011119/21418419/19383fd0-c85c-11e6-86b5-25a6d986e6b1.png)

**Comment by afc163** [comment]
ok，但是 svg-sprite-loader 还是要安装。

**Comment by pigcan** [comment]
予以支持，但是为了不影响以往的业务，只是对 `\.icon\.svg` 的文件使用 svg-sprite-loader

**Comment by afc163** [comment]
@yiminghe @warmhug 这样 antd-mobile 里的 svg 都要改成 `*.icon.svg` 的格式。

**Comment by warmhug** [comment]
不能这样吧，我觉得可以不用支持了
