### ISSUE TITLE
打包报错，内存溢出

### ISSUE THREAD

**Issue by shapenlone** [ant-tool/atool-build#233]
打包时报错，内存溢出
> jndemo-antd@1.1.1 build /svn/test/test
> atool-build -o ./dist/${npm_package_family}/${npm_package_name}/${npm_package_version}

<--- Last few GCs --->

  145305 ms: Mark-sweep 1361.7 (1457.6) -> 1364.3 (1457.6) MB, 1170.7 / 0 ms [allocation failure] [GC in old space requested].
  146497 ms: Mark-sweep 1364.3 (1457.6) -> 1364.3 (1457.6) MB, 1191.4 / 0 ms [allocation failure] [GC in old space requested].
  147686 ms: Mark-sweep 1364.3 (1457.6) -> 1360.1 (1457.6) MB, 1189.5 / 0 ms [last resort gc].
  148908 ms: Mark-sweep 1360.1 (1457.6) -> 1361.6 (1457.6) MB, 1221.8 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1a983ffe3ac1 <JS Object>
    1: hasOwnProperty [native v8natives.js:~111] [pc=0x1eef80b438d6] (this=0x24cd076e5779 <an Object with map 0x2849c99ad7d1>,B=0x13b87ee815c9 <String[16]: _React$Component>)
    2: addMapping(aka SourceMapGenerator_addMapping) [/svn/test/test/node_modules/source-map/lib/source-map-generator.js:~94] [pc=0x1eef80c10ddc] (this=0x24cd076e4e09 <a SourceMapGenerator ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6

**Comment by pigcan** [comment]
webpack.config.js 看看

**Comment by shapenlone** [comment]
// Learn more on how to config.
// - https://github.com/ant-tool/atool-build#配置扩展

const webpack = require('atool-build/lib/webpack');
const fs = require('fs');
const path = require('path');
const glob = require('glob');

module.exports = function(webpackConfig) {
  webpackConfig.babel.plugins.push('transform-runtime');
  webpackConfig.babel.plugins.push(['antd', {
    style: 'css',  // if true, use less
  }]);

  // Enable this if you have to support IE8.
  // webpackConfig.module.loaders.unshift({
  //   test: /\.jsx?$/,
  //   loader: 'es3ify-loader',
  // });




  const dev = process.env.NODE_ENV === 'development' || process.argv.findIndex((arg) => arg.includes('hmr')) > 0;
  if (dev) {
    console.log('development 环境');
    webpackConfig.output = Object.assign({}, webpackConfig.output, {
      publicPath: '/',
    });
  }

  // 添加一个 DefinePlugin 来处理项目里面的预留值
  webpackConfig.plugins.push(
    new webpack.DefinePlugin({
      __DEV__: JSON.stringify(dev),
      __BASENAME__: JSON.stringify(process.env.BASENAME || ''),
    })
  );






  // Parse all less files as css module.
  webpackConfig.module.loaders.forEach(function(loader, index) {
    if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.less$') > -1) {
      loader.test = /\.dont\.exist\.file/;
    }
    if (loader.test.toString() === '/\\.module\\.less$/') {
      loader.test = /\.less$/;
    }
  });

  // Load src/entries/*.js as entry automatically.
  const files = glob.sync('./src/entries/*.js');
  const newEntries = files.reduce(function(memo, file) {
    const name = path.basename(file, '.js');
    memo[name] = file;
    return memo;
  }, {});
  webpackConfig.entry = Object.assign({}, webpackConfig.entry, newEntries);

  return webpackConfig;
};

**Comment by sorrycc** [comment]
阅读困难，请调整下格式，https://guides.github.com/features/mastering-markdown/ 。

**Comment by shapenlone** [comment]
调整了格式，能帮忙看下么？

**Comment by pigcan** [comment]
你是司内的?

**Comment by shapenlone** [comment]
不是

**Comment by pigcan** [comment]
配置应该没有什么问题是否能提供复现案例

另外可以提供下对应进程的 dump 文件看看

**Comment by pigcan** [comment]
之前解决过相关案例是系统本身就没有多少内存了。

**Comment by shapenlone** [comment]
@pigcan dump文件太大咯。系统还剩余5g内存。郁闷中

**Comment by fomenyesu** [comment]
我也遇到了这个问题。@shapenlone @pigcan

**Comment by pigcan** [comment]
node 内存溢出查看过一些文章，比较靠谱的说法是，node 本身就有内存的限制的，在 32位 机器上是 512 MB， 64位则是 1GB，但有些地方也说 64 位默认可分配最大内存空间是 1.4 或 1.7GB， 看不到具体的结论。

但可以确定的是node 本身就有内存的限制的，这和你本地有多大的内存并没有决定性的关联。

如 @fomenyesu 所说可以通过 --max-old-space-size=2048 这一类的方式加大 node 分配的内存，具体可以看看 angular 社区提出的问题 https://github.com/angular/angular/issues/5229



另外引起这个问题在公司业务中看到的是，很多人会使用单页应用的方案，所以会把上百个脚本文件只打到一个脚本中。这种情况，会非常容易必现 OOM 的情况。在这一类情况下，建议合理的 split 你的代码，可以通过 vendor 、externals、require.ensure 等等。

**Comment by xflife** [comment]
```
const webpack = require('atool-build/lib/webpack');

module.exports = function (webpackConfig, env) {
  webpackConfig.babel.plugins.push('transform-runtime');
  //babel-plugin-import 是用来按需加载 antd 的脚本和样式的
  webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd',
    style: 'css',
  }]);

  // Support hmr
  if (env === 'development') {
    webpackConfig.devtool = '#eval';
    webpackConfig.babel.plugins.push('dva-hmr');
  } else {
    webpackConfig.babel.plugins.push('dev-expression');
  }

  // Don't extract common.js and common.css
  webpackConfig.plugins = webpackConfig.plugins.filter(function (plugin) {
    return !(plugin instanceof webpack.optimize.CommonsChunkPlugin);
  });

  // Support CSS Modules
  // Parse all less files as css module.
  webpackConfig.module.loaders.forEach(function (loader, index) {
    if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.less$') > -1) {
      loader.include = /node_modules/;
      loader.test = /\.less$/;
    }
    if (loader.test.toString() === '/\\.module\\.less$/') {
      loader.exclude = /node_modules/;
      loader.test = /\.less$/;
    }
    if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.css$') > -1) {
      loader.include = /node_modules/;
      loader.test = /\.css$/;
    }
    if (loader.test.toString() === '/\\.module\\.css$/') {
      loader.exclude = /node_modules/;
      loader.test = /\.css$/;
    }
  });


  webpackConfig.module.loaders.push({
    test   : /\.woff/,
    loader : 'url?prefix=font/&limit=10000&mimetype=application/font-woff'
  })
  webpackConfig.module.loaders.push({
    test   : /\.ttf/,
    loader : 'file?prefix=font/'
  })
  webpackConfig.module.loaders.push({
    test   : /\.eot/,
    loader : 'file?prefix=font/'
  })
  webpackConfig.module.loaders.push({
    test   : /\.svg/,
    loader : 'file?prefix=font/'
  })
  
  return webpackConfig;
};

```

webpack配置如上，项目中也用了 require.ensure 进行分割，在开发中没有问题，但是打包时候出现内存溢出问题，用的 dva-cli 框架，机器以及系统 mac ox 10.12.2 13-inch Early 2015_

**Comment by DylanMay** [comment]
也用了代码分割，也是用atool-build打包

**Comment by LDD123** [comment]
你好，内存溢出怎么增加的node.js内存啊，不知道加在哪里
