### ISSUE TITLE
如何使用url-loader

### ISSUE THREAD

**Issue by miaoyinjun** [ant-tool/atool-build#234]
url：处理 .woff, .woff2, .ttf, .svg, png, jpg, jpeg, gif 文件
如何加入ebpack.config.js

**Comment by pigcan** [comment]
已经内置

**Comment by miaoyinjun** [comment]
请问如何调用和使用，谢谢

**Comment by pigcan** [comment]
样式照常写，构建运行 atool-build

**Comment by miaoyinjun** [comment]
webpack.config.js怎么用
