### ISSUE TITLE
是否没有增加 async/await 配置

### ISSUE THREAD

**Issue by popomore** [ant-tool/atool-build#236]

**Comment by popomore** [comment]
好像是没加 generatoe runtime

**Comment by pigcan** [comment]
之后 atool-build 中会内置，目前需要可以在 webpack.config.js 中添加 babel-plugin-transfrom-runtime, 并在自己的 deps 依赖中添加 babel-runtime

**Comment by popomore** [comment]
内置后会不会很大

**Comment by pigcan** [comment]
还好吧 现在 antd 的脚手架好像就内置了

**Comment by popomore** [comment]
好像

**Comment by popomore** [comment]
已经支持了？
