### ISSUE TITLE
atool-build

### ISSUE THREAD

**Issue by zdxxxxxx** [ant-tool/atool-build#237]
webpack.config.js：
export function(webpackConfig,env){
   console.log(env)
} 
undefined

想通过env 配置不同的webpack

**Comment by tsyeyuanfeng** [comment]
我看之前的代码是会传environment变量给webpack.config.js中定义的function的，但是为什么后来删掉了呢？

**Comment by pigcan** [comment]
直接使用 NODE_ENV 也也可以么

**Comment by zdxxxxxx** [comment]
用NODE_ENV已经解决了
