### ISSUE TITLE
atool-build --watch并没有重新rebuild

### ISSUE THREAD

**Issue by leozim** [ant-tool/atool-build#238]
我预期是js文件有变化的时候，可以自动重新编译，但是并没有，有的时候第一次改变会重新编译，大多数情况下不会，非常的不稳定，或者是我对这个--watch具体是做什么的，理解不正确。
版本是atool-build 0.93
具体的代码，感觉和js没有关系，我在package.json中的配置
{
  "private": true,
  "entry": {
    "index": "./src/index.js"
  },
  "dependencies": {
    "antd": "^2.5.2",
    "babel-plugin-import": "^1.1.0",
    "dva": "^1.1.0",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-router": "^3.0.0"
  },
  "devDependencies": {
    "atool-build": "^0.9.0",
    "atool-test-mocha": "^0.1.5",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-dva-hmr": "^0.2.0",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-runtime": "^6.9.2",
    "expect": "^1.20.2",
    "redbox-react": "^1.3.2"
  },
  "scripts": {
    "start": "atool-build --watch --no-compress",
    "test": "atool-test-mocha ./src/**/*-test.js"
  }
}

**Comment by pigcan** [comment]
一般 start 不是开启 server 么 - -！

可以使用  dora，外加一个 dora-plugin-webpack 就好了。

**Comment by leozim** [comment]
@pigcan ,我后台用的laravel，已经用了nginx，如果再用dora的话，会引起跨域的问题

**Comment by pigcan** [comment]
http://webpack.github.io/docs/node.js-api.html#compiler
具体资料可以查到到这里


另外在我测试中并不会出现说修改 js 但是不重新编译这种情况.  

建议你如果一定要用这种方式，但是 watch 又不能用时

"start": "atool-build"


```bash
tnpm run start -- --watch
```
