### ISSUE TITLE
output问题

### ISSUE THREAD

**Issue by ITtong** [ant-tool/atool-build#239]
![image](https://cloud.githubusercontent.com/assets/19646825/21257221/da7c9ca4-c3b1-11e6-8d2a-87a29f74b033.png)
这是我的目录，我想把qiniu文件夹下的js，避开编译过程，将原文件输出到dist文件夹中。
应该怎么配置？
![image](https://cloud.githubusercontent.com/assets/19646825/21257267/24eaeb9c-c3b2-11e6-94f9-02afc000fb3b.png)
![image](https://cloud.githubusercontent.com/assets/19646825/21257274/2d0e0c1e-c3b2-11e6-9ef1-4d9086aaa534.png)
这是我的webpack.config.js文件。

**Comment by infeng** [comment]
在webpack.config.js设置externals，参考[externals](http://webpack.github.io/docs/configuration.html#externals)

**Comment by pigcan** [comment]
一种方案是通过 externals 把 qiniu 下的脚本声明为一个外部依赖，然后在 html 中引入一个 cdn 地址 抑或是通过 webpack copy 的插件把你的外部依赖拷贝到 dist 下，在 html 中记入相对地址。

另外还可以使用 vendor + noParse
