### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined，不想悲剧重演

### ISSUE THREAD

**Issue by zuiidea** [ant-tool/atool-build#240]
问题是这样的，第一次编译正常，一旦修改某个文件再编译时，控制台报错Uncaught TypeError: Cannot read property 'apply' of undefined，之后无论做什么修改都会报这个错，除非重编

解决方案：https://github.com/webpack/webpack/issues/583

即是禁用DedupePlugin这个插件

**Comment by pigcan** [comment]
感谢提醒. 
目前在分支一当中已经做了相关处理

在 watch 模式下优化类插件 extract  uglify 应该都被关闭。

**Comment by zhangjh** [comment]
这个真的是很无语，我曾经在查这个问题上差点三观崩溃。。因为就单单是注释下都会报这个错

**Comment by zhangjh** [comment]
@pigcan 这个问题新版的atool-build修复了吗？我升级到了0.10.0-alpha.0版本，这个问题依旧存在。。
