### ISSUE TITLE
建议打包时加入版本控制

### ISSUE THREAD

**Issue by Jessie-D** [ant-tool/atool-build#243]
建议打包时加入版本控制，静态资源加入版本号，维护升级后用户不再清除本地缓存也可以用

**Comment by ranchoX** [comment]
我是添加以下代码实现的 清除缓存的
`
webpackConfig.module.loaders = webpackConfig.module.loaders.filter(function (loader) {
    return loader.test.toString() != '/\\.html?$/';
  })
`

`for (let key in webpackConfig.entry) {
    webpackConfig.plugins.push(new HtmlWebpackPlugin({
      filename: `${key}.html`,
      hash: true,
      minify: {
        removeComments: true
      },
      template: path.resolve(__dirname, webpackConfig.entry[key].replace('.js', '.html'))
    }))
  }`

**Comment by pigcan** [comment]
用 hash 方案不就可以么.

**Comment by Jessie-D** [comment]
图片，css ,js都可以做到么， @pigcan 能具体讲一下吗

**Comment by pigcan** [comment]
`atool-build --hash`
