### ISSUE TITLE
支持 css hot reload

### ISSUE THREAD

**Issue by shepherdwind** [ant-tool/atool-build#247]
现在默认开启了 extract-text-webpack-plugin ，而这个插件是不支持 css 热加载的。

现在用得比较多的一般是开发环境不使用 extract-text-webpack-plugin ，然后使用 style-loader 。在发布到线上环境才使用 extract-text-webpack-plugin 。

建议：使用 style-loader ，并且增加开关关闭 extract-text-webpack-plugin 。

**Comment by pigcan** [comment]
css 的话目前使用 dora-plugin-livereload 也能实现 hot-reload

**Comment by iiitmahesh** [comment]
@shepherdwind can please share webpack config for this???

**Comment by shepherdwind** [comment]
@iiitmahesh css hot reload can support by my plugin https://github.com/shepherdwind/css-hot-loader .

If you use atool-build, you should modify webpack.config.js, add css-hot-loader plugin

```js
    webpackConfig.module.loaders.map(mod => {
      if (!mod.loader) {
        return;
      }

      if (mod.loader.includes('extract-text-webpack-plugin')) {
        mod.loader = `css-hot-loader!${mod.loader}`;
      }
    });
```
