### ISSUE TITLE
给--hash的实现一点小建议

### ISSUE THREAD

**Issue by jiuhuan** [ant-tool/atool-build#252]
建议map-json-webpack-plugin插件参数`assetsPath`的取值建议不要使用package的name。

![image](https://cloud.githubusercontent.com/assets/5218417/22725499/bccd1a54-ee08-11e6-8965-4c366f423b46.png)

**Comment by pigcan** [comment]
这个取名应该是对应的业务场景里面的. 应该不可能 atool-build 层面更改. 

如果要修改，建议尝试修改 webpack.config.js 来修改

**Comment by jiuhuan** [comment]
取名是没问题的，问题是为什么要取自package的name字段，这会造成很多困扰

**Comment by pigcan** [comment]
当初和后端那边的约定而已.  不必纠结吧 - -！
