### ISSUE TITLE
Deprecation notice: CommonsChunkPlugin now only takes a single argument. Either an options

### ISSUE THREAD

**Issue by sanyueyu** [ant-tool/atool-build#256]
plugins: [
      new webpack.optimize.CommonsChunkPlugin('common', commonName),
      new ExtractTextPlugin(cssFileName, {
        disable: false,
        allChunks: true,
      }),
      new webpack.optimize.OccurenceOrderPlugin(),
      new CaseSensitivePathsPlugin(),
    ],
  };
}

此处报错信息
Example: if your old code looked like this:
	new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js')
You would change it to:
	new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.bundle.js' })
The available options are:
	name: string
	names: string[]
	filename: string
	minChunks: number
	chunks: string[]
	children: boolean
	async: boolean
	minSize: number

**Comment by aty1990** [comment]
How to solve this error

**Comment by pigcan** [comment]
应该是版本问题吧.

出现这类情况通常是自行在 pkg 中引入了高版本的 webpack 或者非兼容的比如 extractCss 这些

另外如果你是使用的是 atool-build 那么你在覆盖内置配置时，请使用 webpack.config.js
