### ISSUE TITLE
使用了CommonsChunkPlugin 后如何优化antd加载

### ISSUE THREAD

**Issue by pmg1989** [ant-tool/atool-build#257]
烦请问下，我webpack按需加载打包的时候，使用了CommonsChunkPlugin，配置如下图，打包运行其实都没有问题。
![image](https://cloud.githubusercontent.com/assets/13361827/23647691/162b58f0-0352-11e7-9929-907c2ae58acd.png)
但我看到antd官网提及优化antd加载时需使用babel-plugin-import，
![image](https://cloud.githubusercontent.com/assets/13361827/23647780/9b4cc4b0-0352-11e7-81fc-19e8a418f5f7.png)
而babel-plugin-import中又有如下Note，
![image](https://cloud.githubusercontent.com/assets/13361827/23647795/af6812a6-0352-11e7-82a3-74d9f6f33bff.png)
所以我现在很有疑问是不是使用了vendor之后，babel-plugin-import对于antd的优化加载已经无效。
但我不用vendor，打包的文件又会变得很大，请问这种情况下可以怎么优化呢？

**Comment by pigcan** [comment]
可以使用 externals 把你 common 内的大部分模块都申明为外部依赖，这样 webpack 就不会打包这些模块，但需要你在 html 中引入对应的模块 通过 script 外链方式

antd 你正常通过 import 方式 然后配合 babel-plugin-import 即可
