### ISSUE TITLE
在atool-build中如何使用webpack的代理功能（webpack-dev-server）

### ISSUE THREAD

**Issue by jingchenxu** [ant-tool/atool-build#258]
在使用 atool-build 和 dora 时如何配合后端进行跨域调试？

**Comment by pigcan** [comment]
webpack-dev-server 暂时不能通过 atool-build 来或与支持.  不太清楚这个跨域调试是什么意思

**Comment by jingchenxu** [comment]
@pigcan  谢谢，问题已经解决了，主要是仔细的查看dora文档就能知道了。
