### ISSUE TITLE
theme自定义主题不生效

### ISSUE THREAD

**Issue by onlyLiru** [ant-tool/atool-build#259]
编译也没问题，就是不生效，请问什么原因？（webpack自己搭的脚手架）
![image](https://cloud.githubusercontent.com/assets/7598528/23889023/e66864d6-08c5-11e7-8784-7f1d03157490.png)

**Comment by pigcan** [comment]
自己搭的脚手架是什么意思 ?

自己搞了一份 webpack 的构建配置吗
