### ISSUE TITLE
IE8 下报错不能使用

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#28]
`default` 在 IE8 下是保留字

- http://stackoverflow.com/questions/33512715/babel-6-0-20-modules-feature-not-work-in-ie8
- https://phabricator.babeljs.io/T2817

**Comment by sorrycc** [comment]
https://github.com/spicyj/es3ify

**Comment by sorrycc** [comment]
先通过 webpack loader 的方式解决。
https://github.com/sorrycc/es3ify-loader

不过最终还是等 babel 解决，所以这个方案不放到 atool-build 里，通过自定义 webpack.config.js 的方式解决。参考：https://github.com/ant-design/antd-init/commit/432f4e94a528f2c3fa4976c327b035ac9d5c6574

**Comment by sorrycc** [comment]
issue 先开着，等 babel 解决了再关吧。

**Comment by afc163** [comment]
:+1:

**Comment by zinkey** [comment]
:+1:

**Comment by sorrycc** [comment]
https://github.com/babel/babel/pull/3368
babel 6.6 修复这个问题了

**Comment by afc163** [comment]
是否不再需要 es3ify 了？

**Comment by sorrycc** [comment]
是的，atool-build 升级后就不需要了。

**Comment by afc163** [comment]
atool-build 没人维护啊，一堆 issue 和 pr。

**Comment by sorrycc** [comment]
仔细看了下，并没有解决问题，后面也有人反馈没有解决。。还是继续用 [es3ify-loader](https://github.com/sorrycc/es3ify-loader) 吧。

- https://phabricator.babeljs.io/T6863
- https://phabricator.babeljs.io/T2817

**Comment by sorrycc** [comment]
https://github.com/ant-design/ant-design/issues/1217

**Comment by afc163** [comment]
呃...

**Comment by zinkey** [comment]
方案：

使用https://github.com/spicyj/es3ify 解决
