### ISSUE TITLE
提示弹窗，能不能给关了。

### ISSUE THREAD

**Issue by phnessu4** [ant-tool/atool-build#301]
新版本的编译提示，编译代码的时候，代码自动hotload，写代码的时候，mac的提示就叮叮叮的一直响，烦死了快。

找了半天也没找到参数开关，有没有什么办法给屏蔽了。

**Comment by pigcan** [comment]
现在是没法关闭的  之后我加个 silent 功能吧

**Comment by phnessu4** [comment]
有劳～
