### ISSUE TITLE
是否内置大小写检查插件?

### ISSUE THREAD

**Issue by fangk** [ant-tool/atool-build#302]
是否可以内置这个插件: https://github.com/Urthen/case-sensitive-paths-webpack-plugin

很多业务老是碰到大小写问题. 都是本地能通过, 到服务端构建就挂了.

**Comment by fangk** [comment]
https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L201

原来这里已经支持了.  atool-build 什么时候发 1.0 啊.  让大家直接 ^1.0.0 去引用不就好了么?

**Comment by pigcan** [comment]
今天发了 1.0 了
