### ISSUE TITLE
关于引css报错问题 extract-text-webpack-plugin

### ISSUE THREAD

**Issue by zyxpz** [ant-tool/atool-build#306]
![image](https://user-images.githubusercontent.com/21350325/29660690-8485c18c-88f4-11e7-91bd-1bcfac5dac5d.png)
如图，有没有解决方案呢？

**Comment by yesmeck** [comment]
提供下重现  repo？

**Comment by zyxpz** [comment]
就拿anima-carousel这个包说吧，我这边 npm run doc 就会报这个错了。。 @yesmeck

**Comment by yesmeck** [comment]
@zyxpz 钉钉找下我 边柳
