### ISSUE TITLE
can has some way to disable webpack dedupe plugins

### ISSUE THREAD

**Issue by sunopar** [ant-tool/atool-build#309]
版本：0.11.1
有没有什么办法可以禁止webpack.optmize.dedupe
我现在的项目出现了一个问题，在build时会卡在optmize阶段，73%左右，无论等多长时间。然后我尝试一步步删掉webpack的plugins。当删掉dedupe插件时，打包速度瞬间提升了很多。之前正常情况下，打包大概需要十分钟（可能是我文件过多的问题，我现在项目大概一百多个页面）。取消掉dedupe后，只需一分钟。

**Comment by soda-x** [comment]
使用 webpack.config.js 然后在返回的对象中删除这个插件就好。

ps 虽然速度快了，但是你的体积肯定会大不少。 老的 webpack 中建议是在 开发环境中不使用 dedupe 生产环境中应用。

**Comment by sunopar** [comment]
非常感谢，我再仔细看看是什么原因导致的

**Comment by soda-x** [comment]
dedupe 会分析你引用的内容 按 module 来，如果判断为重复内容会予以去重。 这部分内容可能是自己的代码 也可能是 node_modules 内的内容。 webpack 2 以上已经内置。
