### ISSUE TITLE
如何在atool-build的webpack配置文件中，添加新plugin？

### ISSUE THREAD

**Issue by doublelduob** [ant-tool/atool-build#32]
``` javascript
webpackConfig.plugins.push(
    new webpack.DefinePlugin({
      __DEV__: JSON.stringify(JSON.parse(process.env.BUILD_DEV || 'true')),
      __PRERELEASE__: JSON.stringify(JSON.parse(process.env.BUILD_PRERELEASE || 'false'))
    })
  );
```
会报错，说webpack not defined

**Comment by sorrycc** [comment]
```
var webpack = require('atool-build/lib/webpack');
```

**Comment by doublelduob** [comment]
非常感谢

**Comment by Jamesxiehailong** [comment]
如何在这个使用了atool-build的项目中，配置反向代理，有的时候开发环境需要转发cookie和token等字段

**Comment by Jamesxiehailong** [comment]
webpackConfig.devServer = {
    historyApiFallback: true,
        contentBase: "./",
        quiet: false, //控制台中不输出打包的信息
        noInfo: false,
        hot: true, //开启热点
        inline: true, //开启页面自动刷新
        lazy: false, //不启动懒加载
        progress: true, //显示打包的进度
        watchOptions: {
            aggregateTimeout: 300
        },
        port: '8088', //设置端口号
       proxy: {
      '/admin/*': {
        target: 'http://XXXXXX:9100/',
        secure: true
      }
    }
  }
