### ISSUE TITLE
Compile less with IE hack will have error message

### ISSUE THREAD

**Issue by qiuyuntao** [ant-tool/atool-build#47]
```
@base_url: './images/';

.backgroundImage(@url) {
  background-image: url('@{base_url}@{url}.png');
  background-image: e("url('@{base_url}x/@{url}.png')\9");
}


#root {
  .backgroundImage('alipayIcon');
}

```
write like this, with `atool`, it will fail to compile `less`.

Then I write a `webpack loader` demo to compile this,

```
module.exports = {
    entry: "./entry.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style!css" },
            { test: /\.less$/, loader: "style!css!less" },
            { test: /\.png$/, loader: "url-loader?mimetype=image/png" }
        ]
    }
};
```

It can work well, so it seems a `atool` problem to compile `less`

[compile this online](http://less2css.org/#%7B%22less%22%3A%22%40base_url%3A%20'.%2Fimages%2F'%3B%5Cn%5Cn.backgroundImage(%40url)%20%7B%5Cn%20%20background-image%3A%20url('%40%7Bbase_url%7D%40%7Burl%7D.png')%3B%5Cn%20%20background-image%3A%20e(%5C%22url('%40%7Bbase_url%7Dx%2F%40%7Burl%7D.png')%5C%5C9%5C%22)%3B%5Cn%7D%5Cn%5Cn%23demo%20%7B%5Cn%20%20.backgroundImage('large_cloud')%3B%5Cn%7D%22%7D)

**Comment by zinkey** [comment]
```javascript
module.exports = {
    entry: "./index.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style!css" },
            { test: /\.less$/, loader: "style!css!less" },
            { test: /\.png$/, loader: "url-loader?limit=10000&mimetype=image/png" }
        ]
    }
};
```
will fail (image size > limit=10000)

**Comment by zinkey** [comment]
background-image: e() dir error
