### ISSUE TITLE
autoprefixer-loader 替换为 postcss-loader

### ISSUE THREAD

**Issue by pigcan** [ant-tool/atool-build#49]
```bash
npm WARN deprecated autoprefixer-loader@3.1.0: Please use postcss-loader instead of autoprefixer-loader
```

在 `spm`  中已经使用 `postcss` 许久了 

目前发现和以往有差异的点就是 顺序问题 .

举个例子

`a.js` 中 `require` 了  `a.css`  和 `b.css`
`b.js` 中 `require` 了  `b.css`  和 `a.css`

在 `postcss` 是会报错.  严格意义上这是正确的，因为 `a.css` 和 `b.css` 完全可能存在覆盖的关系.

**Comment by zinkey** [comment]
> ### :warning: This module is deprecated. [Autoprefixer official page](https://github.com/postcss/autoprefixer#webpack) recommends using [`postcss-loader`](https://github.com/postcss/postcss-loader) instead.

是需要采用 postcss-loader
