### ISSUE TITLE
构建详细日志通过参数呈现

### ISSUE THREAD

**Issue by pigcan** [ant-tool/atool-build#50]
![image](https://cloud.githubusercontent.com/assets/848515/12414186/ce669660-bece-11e5-90ae-a266ad4c4c88.png)

让用户自己去选择是否需要详细日志  比如 `--verbose`

默认就给个简化的日志.

**Comment by zinkey** [comment]
这个可以通过配置 webpack.config.js 来实现

**Comment by sorrycc** [comment]
也不会太简化，只隐藏 uglifyjs 的 warn 信息吧，这个很长一段，而且没啥用。

**Comment by zinkey** [comment]
那就只“隐藏 uglifyjs 的 warn 信息”，也不需要--verbose

**Comment by saiyagg** [comment]
已完成：隐藏uglifyjs 的 warning 信息

**Comment by sorrycc** [comment]
pure_getters, unsafe, screw_ie8, comparisons 的含义调研过了吗?

**Comment by saiyagg** [comment]
我先把这几个开关去掉，待讨论后再决定是否开启
