### ISSUE TITLE
map.json 路径生成异常

### ISSUE THREAD

**Issue by pigcan** [ant-tool/atool-build#54]
如果用户现在设置 `webpack.config.js` 配置如下

```javascript
module.exports = function(webpackConfig) {
  webpackConfig.output = {
    path: join(process.cwd(), './www/')
  };
  return webpackConfig;
};
```
那么会导致文件生成在  `www` 目录下  而 `dist` 下 生成 `map.json`

原因出在这儿

https://github.com/ant-tool/atool-build/blob/master/src/build.js#L45

这对我们对外说的 `webpack.config.js` 可以覆盖内部逻辑不太相符合.

这边衍生出来的另外一个问题是 如果用户在现有基础上只是需要再多配置一个  `publicPath`

那么目前是办不到.  因为自定义的 ` webpackConfig.output` 会覆盖 `atool-build` 自带的 `output` , 后续对这一块需求如何考虑?

**Comment by zinkey** [comment]
这里是不好处理，但是配置原则是：

1. 采用 atool-build 配置来；

2. 如果第一条无法满足，用 webpack.config.js。

对于 hash 那个问题，其实就是：`先 merge 还是后merge 用户配置`

现在采用的是后 merge 用户配置，也就是 webpack.config.js 可以覆盖之前的所有配置，所以要是这样写了：

```javascript
module.exports = function(webpackConfig) {
  webpackConfig.output = {
    path: join(process.cwd(), './www/')
  };
  return webpackConfig;
};
```

又这样用了：

```bash
$ atool-build --hash
```

其实就是用户要自己写 webpack 配置了，这里就让用户写好了。内置的配置都可以覆盖。

后续看是否可以有 atool-build --webpack 直接输出一份内置的 webpack 配置文件，用户直接在修改。

**Comment by sorrycc** [comment]
https://github.com/ant-tool/atool-build/blob/master/src/build.js#L45
只升级依赖应该不够，这一行要去掉吧。
