### ISSUE TITLE
`atool-server` 社区版什么时候发布？

### ISSUE THREAD

**Issue by helloyou2012** [ant-tool/atool-build#56]
`atool-server` 预计什么时候发布社区版？实在等不及了，仿照atool又造了个轮子（⊙﹏⊙b汗）[https://github.com/d-band/dool](https://github.com/d-band/dool)，支持：

- `package.json` 中files转entry
- 利用 `gauge` 和 `ProgressPlugin` 显示进度
- 移除了`CommonsChunkPlugin`
- `webpack` 暴露给`webpack.config.js`

> 目前server直接调用的`webpack-dev-server`，坐等atool-server啊！！！！

**Comment by zinkey** [comment]
没有 atool-server，调试请采用 [dora](https://github.com/dora-js/dora) 及 [dora-plugin-atool-build](https://github.com/dora-js/dora-plugin-atool-build)。

```bash
$ dora --plugins atool-build
```

**Comment by sorrycc** [comment]
http://ant-tool.github.io/dora.html
