### ISSUE TITLE
跟进：es6 import 方式的按需打包

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#6]
- https://github.com/rollup/rollup
- https://github.com/webpack/webpack/tree/webpack-2/examples/harmony-unused

**Comment by yiminghe** [comment]
:+1:

**Comment by sorrycc** [comment]
https://github.com/webpack/webpack/releases/tag/v2.0.0-beta
webpack v2.0.0-beta 发布了，可以尝下鲜。

**Comment by sorrycc** [comment]
![image](https://cloud.githubusercontent.com/assets/35128/11246307/1a636d3e-8e52-11e5-91af-095feebf2cd3.png)

webpack 2 的 tree shake 还有个问题，引用如上图，理论上只需要 a + b1，实际上是 a + b1 + c1。

**Comment by sorrycc** [comment]
antd 通过 babel 插件的方式解决。https://github.com/ant-design/babel-plugin-antd

**Comment by pigcan** [comment]
顶顶

**Comment by pigcan** [comment]
由 https://github.com/ant-tool/atool-build/issues/64 中跟进
