### ISSUE TITLE
开启 babel-loader 的缓存功能，重复构建时性能应该可以提升一倍

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#66]
https://github.com/babel/babel-loader

**Comment by sorrycc** [comment]
试了下 babel-loader 的 cacheDirectory，基本没啥用，因为 babel 只作用于项目代码，对于大部分的 node_modules 下的文件是无效的。

**Comment by sorrycc** [comment]
- https://github.com/mzgoddard/webpack-cache-module-plugin
- https://github.com/bholloway/persistent-cache-webpack-plugin

后续有空再试试这两个插件。

**Comment by pigcan** [comment]
之前在官方那个 issue 平台看到过默认是忽略 node_modules 的，但是可以人为去指定需要 .

**Comment by pigcan** [comment]
已经开启
