### ISSUE TITLE
不同几个entry可共同提取的公共模块不一定一致，atool-build怎么解决？

### ISSUE THREAD

**Issue by LichK** [ant-tool/atool-build#67]
假设以下场景：
>定义`entry: [page1, page2, page3, page4]`。`page1`与`page2`可共同提取模块`com1`，`page3`与`page4`可共同提取模块`com2`

查阅文档，感觉根据atto-build目前的配置，只能通过所有entry单独提取一个最大的公共模块，可这样会造成js文件十分庞大，没有意义地占用带宽。
请问如果使用atool-build，可否支持分开提取公共模块？

另，可以开放webpack的所有配置接口吗？这样感觉上也会比较灵活

**Comment by pigcan** [comment]
可以覆盖现有配置 

参考该文档 http://ant-tool.github.io/spm-to-atool-build.html
