### ISSUE TITLE
When use atool-build will report module can't be found error

### ISSUE THREAD

**Issue by qiuyuntao** [ant-tool/atool-build#80]
When I use antd-init to initial my project, then use atool-build, it will report `Cannot find module 'core-js/library/fn/get-iterator'` error.

![GitHub Logo](http://chuantu.biz/t2/25/1455343503x-954497768.png)

I search node_modules, module `core-js` is in it. So I'm confuse about why it report this error.

**Comment by sorrycc** [comment]
try npm3
