### ISSUE TITLE
0.1.0

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#9]
## 进展

- [x] 代码规范约定，基于 `pre-commit` + `eslint` + `airbnb/es6`
- [x] 基于 es6 编码，通过 babel 自动转成 es5
- [x] 升级到 babel 6，https://github.com/ant-tool/atool-build/pull/7
- [x] 基于 Jest 完善测试用例
- [x] 优化自定义配置的实现，使用方法详见：https://github.com/ant-tool/atool-build#配置扩展
- [x] 支持 `--hash`，https://github.com/ant-tool/atool-build/issues/4
- [x] 支持 `--devtool`，默认不输出 sourcemap
- [x] 修复 `process.exit` 退出码不正确的问题，https://github.com/ant-tool/atool-build/commit/9f2d65b034681b2a0fa17d7817a6a963a39cbddb
- [x] 文档
- [ ] 整合 react 生产环境的插件，https://github.com/ant-tool/atool-build/issues/8
- [ ] 由于 babel 6 在 npm2 下使用异常缓慢，检测到 npm2 时给出提示 (抽成单独的一个库)

**Comment by yiminghe** [comment]
pre-commit
