### ISSUE TITLE
tnpm@4

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-build#93]
两个问题：

1. 是否兼容，主要是改写了 babel-core 的 resolve，看下路径是否有问题
2. babel 运行是否缓慢

**Comment by fengmk2** [comment]
都通过 `require.resolve('moduleName')` 找到模块路径即可。

**Comment by fengmk2** [comment]
@dead-horse 找到问题所在 https://github.com/sorrycc/babel-core-resolve-enhance/blob/master/src/index.js#L17

**Comment by fengmk2** [comment]
最好不要这样 patch。。。

**Comment by dead-horse** [comment]
这是用来解决 npm2 的问题的么？

**Comment by sorrycc** [comment]
@dead-horse 是的。
@fengmk2 babel 不支持自定义 resolve 路径，暂时只能这样。

**Comment by fengmk2** [comment]
@dead-horse 按你的建议来支持这个吧。

**Comment by fengmk2** [comment]
https://github.com/cnpm/npminstall/pull/19

**Comment by fengmk2** [comment]
@sorrycc 给 babel-core-resolve-enhance 加单元测试？

**Comment by sorrycc** [comment]
👍，用例我加下。

**Comment by sorrycc** [comment]
babel-core-resolve-enhance 后面不用了，通过 `require.resolve` 处理。 #112
